//** THIS FILE IS AUTOGENERATED, DO NOT MODIFY DIRECTLY.  */
import cpp
import RuleMetadata

newtype ToolchainQuery =
  TFloatingPointImplementationShallComplyWithIeeeStandardQuery() or
  TCompilerImplementationShallComplyWithCPP14StandardQuery() or
  TIncrementOperatorWithBoolOperandIsDeprecatedQuery() or
  TRegisterKeywordIsDeprecatedQuery() or
  TImplicitCopyConstructorIsDeprecatedQuery() or
  TImplicitCopyAssignmentOperatorIsDeprecatedQuery() or
  TDynamicExceptionsAreDeprecatedQuery() or
  TCStandardLibraryHeadersAreDeprecatedQuery() or
  TStrstreamTypesAreDeprecatedQuery() or
  TCompilerWarningLevelNotInComplianceQuery() or
  TUncompliantOptimizationOptionMustBeDisabledInCompilerQuery()

predicate isToolchainQueryMetadata(Query query, string queryId, string ruleId) {
  query =
    // `Query` instance for the `floatingPointImplementationShallComplyWithIeeeStandard` query
    ToolchainPackage::floatingPointImplementationShallComplyWithIeeeStandardQuery() and
  queryId =
    // `@id` for the `floatingPointImplementationShallComplyWithIeeeStandard` query
    "cpp/autosar/floating-point-implementation-shall-comply-with-ieee-standard" and
  ruleId = "A0-4-1"
  or
  query =
    // `Query` instance for the `compilerImplementationShallComplyWithCPP14Standard` query
    ToolchainPackage::compilerImplementationShallComplyWithCPP14StandardQuery() and
  queryId =
    // `@id` for the `compilerImplementationShallComplyWithCPP14Standard` query
    "cpp/autosar/compiler-implementation-shall-comply-with-cpp14standard" and
  ruleId = "A0-4-3"
  or
  query =
    // `Query` instance for the `incrementOperatorWithBoolOperandIsDeprecated` query
    ToolchainPackage::incrementOperatorWithBoolOperandIsDeprecatedQuery() and
  queryId =
    // `@id` for the `incrementOperatorWithBoolOperandIsDeprecated` query
    "cpp/autosar/increment-operator-with-bool-operand-is-deprecated" and
  ruleId = "A1-1-1"
  or
  query =
    // `Query` instance for the `registerKeywordIsDeprecated` query
    ToolchainPackage::registerKeywordIsDeprecatedQuery() and
  queryId =
    // `@id` for the `registerKeywordIsDeprecated` query
    "cpp/autosar/register-keyword-is-deprecated" and
  ruleId = "A1-1-1"
  or
  query =
    // `Query` instance for the `implicitCopyConstructorIsDeprecated` query
    ToolchainPackage::implicitCopyConstructorIsDeprecatedQuery() and
  queryId =
    // `@id` for the `implicitCopyConstructorIsDeprecated` query
    "cpp/autosar/implicit-copy-constructor-is-deprecated" and
  ruleId = "A1-1-1"
  or
  query =
    // `Query` instance for the `implicitCopyAssignmentOperatorIsDeprecated` query
    ToolchainPackage::implicitCopyAssignmentOperatorIsDeprecatedQuery() and
  queryId =
    // `@id` for the `implicitCopyAssignmentOperatorIsDeprecated` query
    "cpp/autosar/implicit-copy-assignment-operator-is-deprecated" and
  ruleId = "A1-1-1"
  or
  query =
    // `Query` instance for the `dynamicExceptionsAreDeprecated` query
    ToolchainPackage::dynamicExceptionsAreDeprecatedQuery() and
  queryId =
    // `@id` for the `dynamicExceptionsAreDeprecated` query
    "cpp/autosar/dynamic-exceptions-are-deprecated" and
  ruleId = "A1-1-1"
  or
  query =
    // `Query` instance for the `cStandardLibraryHeadersAreDeprecated` query
    ToolchainPackage::cStandardLibraryHeadersAreDeprecatedQuery() and
  queryId =
    // `@id` for the `cStandardLibraryHeadersAreDeprecated` query
    "cpp/autosar/c-standard-library-headers-are-deprecated" and
  ruleId = "A1-1-1"
  or
  query =
    // `Query` instance for the `strstreamTypesAreDeprecated` query
    ToolchainPackage::strstreamTypesAreDeprecatedQuery() and
  queryId =
    // `@id` for the `strstreamTypesAreDeprecated` query
    "cpp/autosar/strstream-types-are-deprecated" and
  ruleId = "A1-1-1"
  or
  query =
    // `Query` instance for the `compilerWarningLevelNotInCompliance` query
    ToolchainPackage::compilerWarningLevelNotInComplianceQuery() and
  queryId =
    // `@id` for the `compilerWarningLevelNotInCompliance` query
    "cpp/autosar/compiler-warning-level-not-in-compliance" and
  ruleId = "A1-1-2"
  or
  query =
    // `Query` instance for the `uncompliantOptimizationOptionMustBeDisabledInCompiler` query
    ToolchainPackage::uncompliantOptimizationOptionMustBeDisabledInCompilerQuery() and
  queryId =
    // `@id` for the `uncompliantOptimizationOptionMustBeDisabledInCompiler` query
    "cpp/autosar/uncompliant-optimization-option-must-be-disabled-in-compiler" and
  ruleId = "A1-1-3"
}

module ToolchainPackage {
  Query floatingPointImplementationShallComplyWithIeeeStandardQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `floatingPointImplementationShallComplyWithIeeeStandard` query
      TToolchainPackageQuery(TFloatingPointImplementationShallComplyWithIeeeStandardQuery())
  }

  Query compilerImplementationShallComplyWithCPP14StandardQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `compilerImplementationShallComplyWithCPP14Standard` query
      TToolchainPackageQuery(TCompilerImplementationShallComplyWithCPP14StandardQuery())
  }

  Query incrementOperatorWithBoolOperandIsDeprecatedQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `incrementOperatorWithBoolOperandIsDeprecated` query
      TToolchainPackageQuery(TIncrementOperatorWithBoolOperandIsDeprecatedQuery())
  }

  Query registerKeywordIsDeprecatedQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `registerKeywordIsDeprecated` query
      TToolchainPackageQuery(TRegisterKeywordIsDeprecatedQuery())
  }

  Query implicitCopyConstructorIsDeprecatedQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `implicitCopyConstructorIsDeprecated` query
      TToolchainPackageQuery(TImplicitCopyConstructorIsDeprecatedQuery())
  }

  Query implicitCopyAssignmentOperatorIsDeprecatedQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `implicitCopyAssignmentOperatorIsDeprecated` query
      TToolchainPackageQuery(TImplicitCopyAssignmentOperatorIsDeprecatedQuery())
  }

  Query dynamicExceptionsAreDeprecatedQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `dynamicExceptionsAreDeprecated` query
      TToolchainPackageQuery(TDynamicExceptionsAreDeprecatedQuery())
  }

  Query cStandardLibraryHeadersAreDeprecatedQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `cStandardLibraryHeadersAreDeprecated` query
      TToolchainPackageQuery(TCStandardLibraryHeadersAreDeprecatedQuery())
  }

  Query strstreamTypesAreDeprecatedQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `strstreamTypesAreDeprecated` query
      TToolchainPackageQuery(TStrstreamTypesAreDeprecatedQuery())
  }

  Query compilerWarningLevelNotInComplianceQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `compilerWarningLevelNotInCompliance` query
      TToolchainPackageQuery(TCompilerWarningLevelNotInComplianceQuery())
  }

  Query uncompliantOptimizationOptionMustBeDisabledInCompilerQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `uncompliantOptimizationOptionMustBeDisabledInCompiler` query
      TToolchainPackageQuery(TUncompliantOptimizationOptionMustBeDisabledInCompilerQuery())
  }
}
