//** THIS FILE IS AUTOGENERATED, DO NOT MODIFY DIRECTLY.  */
import cpp
import RuleMetadata

newtype TrustBoundariesQuery =
  TExceptionsThrownAcrossExecutionBoundariesQuery() or
  TDoNotThrowAnExceptionAcrossExecutionBoundariesQuery() or
  TDoNotPassANonstandardObjectAcrossBoundariesQuery()

predicate isTrustBoundariesQueryMetadata(Query query, string queryId, string ruleId) {
  query =
    // `Query` instance for the `exceptionsThrownAcrossExecutionBoundaries` query
    TrustBoundariesPackage::exceptionsThrownAcrossExecutionBoundariesQuery() and
  queryId =
    // `@id` for the `exceptionsThrownAcrossExecutionBoundaries` query
    "cpp/autosar/exceptions-thrown-across-execution-boundaries" and
  ruleId = "A15-1-5"
  or
  query =
    // `Query` instance for the `doNotThrowAnExceptionAcrossExecutionBoundaries` query
    TrustBoundariesPackage::doNotThrowAnExceptionAcrossExecutionBoundariesQuery() and
  queryId =
    // `@id` for the `doNotThrowAnExceptionAcrossExecutionBoundaries` query
    "cpp/cert/do-not-throw-an-exception-across-execution-boundaries" and
  ruleId = "ERR59-CPP"
  or
  query =
    // `Query` instance for the `doNotPassANonstandardObjectAcrossBoundaries` query
    TrustBoundariesPackage::doNotPassANonstandardObjectAcrossBoundariesQuery() and
  queryId =
    // `@id` for the `doNotPassANonstandardObjectAcrossBoundaries` query
    "cpp/cert/do-not-pass-a-nonstandard-object-across-boundaries" and
  ruleId = "EXP60-CPP"
}

module TrustBoundariesPackage {
  Query exceptionsThrownAcrossExecutionBoundariesQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `exceptionsThrownAcrossExecutionBoundaries` query
      TTrustBoundariesPackageQuery(TExceptionsThrownAcrossExecutionBoundariesQuery())
  }

  Query doNotThrowAnExceptionAcrossExecutionBoundariesQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `doNotThrowAnExceptionAcrossExecutionBoundaries` query
      TTrustBoundariesPackageQuery(TDoNotThrowAnExceptionAcrossExecutionBoundariesQuery())
  }

  Query doNotPassANonstandardObjectAcrossBoundariesQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `doNotPassANonstandardObjectAcrossBoundaries` query
      TTrustBoundariesPackageQuery(TDoNotPassANonstandardObjectAcrossBoundariesQuery())
  }
}
