// GENERATED FILE - DO NOT MODIFY
import codingstandards.cpp.rules.enumerationnotdefinedwithanexplicitunderlyingtype_shared.EnumerationNotDefinedWithAnExplicitUnderlyingType_shared

class TestFileQuery extends EnumerationNotDefinedWithAnExplicitUnderlyingType_sharedSharedQuery,
  TestQuery
{ }
