//** THIS FILE IS AUTOGENERATED, DO NOT MODIFY DIRECTLY.  **/
import cpp
import RuleMetadata
import codingstandards.cpp.exclusions.RuleMetadata

newtype Concurrency4Query =
  TCleanUpThreadSpecificStorageQuery() or
  TAppropriateThreadObjectStorageDurationsQuery() or
  TThreadWasPreviouslyJoinedOrDetachedQuery() or
  TDoNotReferToAnAtomicVariableTwiceInExpressionQuery()

predicate isConcurrency4QueryMetadata(Query query, string queryId, string ruleId) {
  query =
    // `Query` instance for the `cleanUpThreadSpecificStorage` query
    Concurrency4Package::cleanUpThreadSpecificStorageQuery() and
  queryId =
    // `@id` for the `cleanUpThreadSpecificStorage` query
    "c/cert/clean-up-thread-specific-storage" and
  ruleId = "CON30-C"
  or
  query =
    // `Query` instance for the `appropriateThreadObjectStorageDurations` query
    Concurrency4Package::appropriateThreadObjectStorageDurationsQuery() and
  queryId =
    // `@id` for the `appropriateThreadObjectStorageDurations` query
    "c/cert/appropriate-thread-object-storage-durations" and
  ruleId = "CON34-C"
  or
  query =
    // `Query` instance for the `threadWasPreviouslyJoinedOrDetached` query
    Concurrency4Package::threadWasPreviouslyJoinedOrDetachedQuery() and
  queryId =
    // `@id` for the `threadWasPreviouslyJoinedOrDetached` query
    "c/cert/thread-was-previously-joined-or-detached" and
  ruleId = "CON39-C"
  or
  query =
    // `Query` instance for the `doNotReferToAnAtomicVariableTwiceInExpression` query
    Concurrency4Package::doNotReferToAnAtomicVariableTwiceInExpressionQuery() and
  queryId =
    // `@id` for the `doNotReferToAnAtomicVariableTwiceInExpression` query
    "c/cert/do-not-refer-to-an-atomic-variable-twice-in-expression" and
  ruleId = "CON40-C"
}

module Concurrency4Package {
  Query cleanUpThreadSpecificStorageQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `cleanUpThreadSpecificStorage` query
      TQueryC(TConcurrency4PackageQuery(TCleanUpThreadSpecificStorageQuery()))
  }

  Query appropriateThreadObjectStorageDurationsQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `appropriateThreadObjectStorageDurations` query
      TQueryC(TConcurrency4PackageQuery(TAppropriateThreadObjectStorageDurationsQuery()))
  }

  Query threadWasPreviouslyJoinedOrDetachedQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `threadWasPreviouslyJoinedOrDetached` query
      TQueryC(TConcurrency4PackageQuery(TThreadWasPreviouslyJoinedOrDetachedQuery()))
  }

  Query doNotReferToAnAtomicVariableTwiceInExpressionQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `doNotReferToAnAtomicVariableTwiceInExpression` query
      TQueryC(TConcurrency4PackageQuery(TDoNotReferToAnAtomicVariableTwiceInExpressionQuery()))
  }
}
