//** THIS FILE IS AUTOGENERATED, DO NOT MODIFY DIRECTLY.  **/
import cpp
import RuleMetadata
import codingstandards.cpp.exclusions.RuleMetadata

newtype Contracts2Query = TExitHandlersMustReturnNormallyQuery()

predicate isContracts2QueryMetadata(Query query, string queryId, string ruleId) {
  query =
    // `Query` instance for the `exitHandlersMustReturnNormally` query
    Contracts2Package::exitHandlersMustReturnNormallyQuery() and
  queryId =
    // `@id` for the `exitHandlersMustReturnNormally` query
    "c/cert/exit-handlers-must-return-normally" and
  ruleId = "ENV32-C"
}

module Contracts2Package {
  Query exitHandlersMustReturnNormallyQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `exitHandlersMustReturnNormally` query
      TQueryC(TContracts2PackageQuery(TExitHandlersMustReturnNormallyQuery()))
  }
}
