//** THIS FILE IS AUTOGENERATED, DO NOT MODIFY DIRECTLY.  **/
import cpp
import RuleMetadata
import codingstandards.cpp.exclusions.RuleMetadata

newtype Contracts7Query =
  TDoNotPassInvalidDataToTheAsctimeFunctionQuery() or
  TDoNotCallVaArgOnAVaListThatHasAnIndeterminateValueQuery() or
  TRightHandOperandOfAShiftRangeQuery() or
  TObjectAssignedToAnOverlappingObjectMisraCQuery() or
  TObjectCopiedToAnOverlappingObjectMisraCQuery()

predicate isContracts7QueryMetadata(Query query, string queryId, string ruleId, string category) {
  query =
    // `Query` instance for the `doNotPassInvalidDataToTheAsctimeFunction` query
    Contracts7Package::doNotPassInvalidDataToTheAsctimeFunctionQuery() and
  queryId =
    // `@id` for the `doNotPassInvalidDataToTheAsctimeFunction` query
    "c/cert/do-not-pass-invalid-data-to-the-asctime-function" and
  ruleId = "MSC33-C" and
  category = "rule"
  or
  query =
    // `Query` instance for the `doNotCallVaArgOnAVaListThatHasAnIndeterminateValue` query
    Contracts7Package::doNotCallVaArgOnAVaListThatHasAnIndeterminateValueQuery() and
  queryId =
    // `@id` for the `doNotCallVaArgOnAVaListThatHasAnIndeterminateValue` query
    "c/cert/do-not-call-va-arg-on-a-va-list-that-has-an-indeterminate-value" and
  ruleId = "MSC39-C" and
  category = "rule"
  or
  query =
    // `Query` instance for the `rightHandOperandOfAShiftRange` query
    Contracts7Package::rightHandOperandOfAShiftRangeQuery() and
  queryId =
    // `@id` for the `rightHandOperandOfAShiftRange` query
    "c/misra/right-hand-operand-of-a-shift-range" and
  ruleId = "RULE-12-2" and
  category = "required"
  or
  query =
    // `Query` instance for the `objectAssignedToAnOverlappingObjectMisraC` query
    Contracts7Package::objectAssignedToAnOverlappingObjectMisraCQuery() and
  queryId =
    // `@id` for the `objectAssignedToAnOverlappingObjectMisraC` query
    "c/misra/object-assigned-to-an-overlapping-object-misra-c" and
  ruleId = "RULE-19-1" and
  category = "mandatory"
  or
  query =
    // `Query` instance for the `objectCopiedToAnOverlappingObjectMisraC` query
    Contracts7Package::objectCopiedToAnOverlappingObjectMisraCQuery() and
  queryId =
    // `@id` for the `objectCopiedToAnOverlappingObjectMisraC` query
    "c/misra/object-copied-to-an-overlapping-object-misra-c" and
  ruleId = "RULE-19-1" and
  category = "mandatory"
}

module Contracts7Package {
  Query doNotPassInvalidDataToTheAsctimeFunctionQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `doNotPassInvalidDataToTheAsctimeFunction` query
      TQueryC(TContracts7PackageQuery(TDoNotPassInvalidDataToTheAsctimeFunctionQuery()))
  }

  Query doNotCallVaArgOnAVaListThatHasAnIndeterminateValueQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `doNotCallVaArgOnAVaListThatHasAnIndeterminateValue` query
      TQueryC(TContracts7PackageQuery(TDoNotCallVaArgOnAVaListThatHasAnIndeterminateValueQuery()))
  }

  Query rightHandOperandOfAShiftRangeQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `rightHandOperandOfAShiftRange` query
      TQueryC(TContracts7PackageQuery(TRightHandOperandOfAShiftRangeQuery()))
  }

  Query objectAssignedToAnOverlappingObjectMisraCQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `objectAssignedToAnOverlappingObjectMisraC` query
      TQueryC(TContracts7PackageQuery(TObjectAssignedToAnOverlappingObjectMisraCQuery()))
  }

  Query objectCopiedToAnOverlappingObjectMisraCQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `objectCopiedToAnOverlappingObjectMisraC` query
      TQueryC(TContracts7PackageQuery(TObjectCopiedToAnOverlappingObjectMisraCQuery()))
  }
}
