//** THIS FILE IS AUTOGENERATED, DO NOT MODIFY DIRECTLY.  **/
import cpp
import RuleMetadata
import codingstandards.cpp.exclusions.RuleMetadata

newtype Declarations1Query =
  TDeclareIdentifiersBeforeUsingThemQuery() or
  TDoNotDeclareOrDefineAReservedIdentifierQuery() or
  TDoNotDeclareAReservedIdentifierQuery() or
  TExternalIdentifiersNotDistinctQuery() or
  TMacroIdentifiersNotDistinctQuery() or
  TMacroIdentifierNotDistinctFromParameterQuery()

predicate isDeclarations1QueryMetadata(Query query, string queryId, string ruleId, string category) {
  query =
    // `Query` instance for the `declareIdentifiersBeforeUsingThem` query
    Declarations1Package::declareIdentifiersBeforeUsingThemQuery() and
  queryId =
    // `@id` for the `declareIdentifiersBeforeUsingThem` query
    "c/cert/declare-identifiers-before-using-them" and
  ruleId = "DCL31-C" and
  category = "rule"
  or
  query =
    // `Query` instance for the `doNotDeclareOrDefineAReservedIdentifier` query
    Declarations1Package::doNotDeclareOrDefineAReservedIdentifierQuery() and
  queryId =
    // `@id` for the `doNotDeclareOrDefineAReservedIdentifier` query
    "c/cert/do-not-declare-or-define-a-reserved-identifier" and
  ruleId = "DCL37-C" and
  category = "rule"
  or
  query =
    // `Query` instance for the `doNotDeclareAReservedIdentifier` query
    Declarations1Package::doNotDeclareAReservedIdentifierQuery() and
  queryId =
    // `@id` for the `doNotDeclareAReservedIdentifier` query
    "c/misra/do-not-declare-a-reserved-identifier" and
  ruleId = "RULE-21-2" and
  category = "required"
  or
  query =
    // `Query` instance for the `externalIdentifiersNotDistinct` query
    Declarations1Package::externalIdentifiersNotDistinctQuery() and
  queryId =
    // `@id` for the `externalIdentifiersNotDistinct` query
    "c/misra/external-identifiers-not-distinct" and
  ruleId = "RULE-5-1" and
  category = "required"
  or
  query =
    // `Query` instance for the `macroIdentifiersNotDistinct` query
    Declarations1Package::macroIdentifiersNotDistinctQuery() and
  queryId =
    // `@id` for the `macroIdentifiersNotDistinct` query
    "c/misra/macro-identifiers-not-distinct" and
  ruleId = "RULE-5-4" and
  category = "required"
  or
  query =
    // `Query` instance for the `macroIdentifierNotDistinctFromParameter` query
    Declarations1Package::macroIdentifierNotDistinctFromParameterQuery() and
  queryId =
    // `@id` for the `macroIdentifierNotDistinctFromParameter` query
    "c/misra/macro-identifier-not-distinct-from-parameter" and
  ruleId = "RULE-5-4" and
  category = "required"
}

module Declarations1Package {
  Query declareIdentifiersBeforeUsingThemQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `declareIdentifiersBeforeUsingThem` query
      TQueryC(TDeclarations1PackageQuery(TDeclareIdentifiersBeforeUsingThemQuery()))
  }

  Query doNotDeclareOrDefineAReservedIdentifierQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `doNotDeclareOrDefineAReservedIdentifier` query
      TQueryC(TDeclarations1PackageQuery(TDoNotDeclareOrDefineAReservedIdentifierQuery()))
  }

  Query doNotDeclareAReservedIdentifierQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `doNotDeclareAReservedIdentifier` query
      TQueryC(TDeclarations1PackageQuery(TDoNotDeclareAReservedIdentifierQuery()))
  }

  Query externalIdentifiersNotDistinctQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `externalIdentifiersNotDistinct` query
      TQueryC(TDeclarations1PackageQuery(TExternalIdentifiersNotDistinctQuery()))
  }

  Query macroIdentifiersNotDistinctQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `macroIdentifiersNotDistinct` query
      TQueryC(TDeclarations1PackageQuery(TMacroIdentifiersNotDistinctQuery()))
  }

  Query macroIdentifierNotDistinctFromParameterQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `macroIdentifierNotDistinctFromParameter` query
      TQueryC(TDeclarations1PackageQuery(TMacroIdentifierNotDistinctFromParameterQuery()))
  }
}
