//** THIS FILE IS AUTOGENERATED, DO NOT MODIFY DIRECTLY.  **/
import cpp
import RuleMetadata
import codingstandards.cpp.exclusions.RuleMetadata

newtype Declarations6Query =
  TFunctionDeclaredImplicitlyQuery() or
  TFlexibleArrayMembersDeclaredQuery() or
  TIdentifiersWithExternalLinkageNotUniqueQuery() or
  TIdentifiersWithInternalLinkageNotUniqueQuery() or
  TInlineFunctionNotDeclaredStaticStorageQuery() or
  TArrayExternalLinkageSizeExplicitlySpecifiedQuery() or
  TShouldNotBeDefinedWithExternalLinkageQuery()

predicate isDeclarations6QueryMetadata(Query query, string queryId, string ruleId, string category) {
  query =
    // `Query` instance for the `functionDeclaredImplicitly` query
    Declarations6Package::functionDeclaredImplicitlyQuery() and
  queryId =
    // `@id` for the `functionDeclaredImplicitly` query
    "c/misra/function-declared-implicitly" and
  ruleId = "RULE-17-3" and
  category = "mandatory"
  or
  query =
    // `Query` instance for the `flexibleArrayMembersDeclared` query
    Declarations6Package::flexibleArrayMembersDeclaredQuery() and
  queryId =
    // `@id` for the `flexibleArrayMembersDeclared` query
    "c/misra/flexible-array-members-declared" and
  ruleId = "RULE-18-7" and
  category = "required"
  or
  query =
    // `Query` instance for the `identifiersWithExternalLinkageNotUnique` query
    Declarations6Package::identifiersWithExternalLinkageNotUniqueQuery() and
  queryId =
    // `@id` for the `identifiersWithExternalLinkageNotUnique` query
    "c/misra/identifiers-with-external-linkage-not-unique" and
  ruleId = "RULE-5-8" and
  category = "required"
  or
  query =
    // `Query` instance for the `identifiersWithInternalLinkageNotUnique` query
    Declarations6Package::identifiersWithInternalLinkageNotUniqueQuery() and
  queryId =
    // `@id` for the `identifiersWithInternalLinkageNotUnique` query
    "c/misra/identifiers-with-internal-linkage-not-unique" and
  ruleId = "RULE-5-9" and
  category = "advisory"
  or
  query =
    // `Query` instance for the `inlineFunctionNotDeclaredStaticStorage` query
    Declarations6Package::inlineFunctionNotDeclaredStaticStorageQuery() and
  queryId =
    // `@id` for the `inlineFunctionNotDeclaredStaticStorage` query
    "c/misra/inline-function-not-declared-static-storage" and
  ruleId = "RULE-8-10" and
  category = "required"
  or
  query =
    // `Query` instance for the `arrayExternalLinkageSizeExplicitlySpecified` query
    Declarations6Package::arrayExternalLinkageSizeExplicitlySpecifiedQuery() and
  queryId =
    // `@id` for the `arrayExternalLinkageSizeExplicitlySpecified` query
    "c/misra/array-external-linkage-size-explicitly-specified" and
  ruleId = "RULE-8-11" and
  category = "advisory"
  or
  query =
    // `Query` instance for the `shouldNotBeDefinedWithExternalLinkage` query
    Declarations6Package::shouldNotBeDefinedWithExternalLinkageQuery() and
  queryId =
    // `@id` for the `shouldNotBeDefinedWithExternalLinkage` query
    "c/misra/should-not-be-defined-with-external-linkage" and
  ruleId = "RULE-8-7" and
  category = "advisory"
}

module Declarations6Package {
  Query functionDeclaredImplicitlyQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `functionDeclaredImplicitly` query
      TQueryC(TDeclarations6PackageQuery(TFunctionDeclaredImplicitlyQuery()))
  }

  Query flexibleArrayMembersDeclaredQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `flexibleArrayMembersDeclared` query
      TQueryC(TDeclarations6PackageQuery(TFlexibleArrayMembersDeclaredQuery()))
  }

  Query identifiersWithExternalLinkageNotUniqueQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `identifiersWithExternalLinkageNotUnique` query
      TQueryC(TDeclarations6PackageQuery(TIdentifiersWithExternalLinkageNotUniqueQuery()))
  }

  Query identifiersWithInternalLinkageNotUniqueQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `identifiersWithInternalLinkageNotUnique` query
      TQueryC(TDeclarations6PackageQuery(TIdentifiersWithInternalLinkageNotUniqueQuery()))
  }

  Query inlineFunctionNotDeclaredStaticStorageQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `inlineFunctionNotDeclaredStaticStorage` query
      TQueryC(TDeclarations6PackageQuery(TInlineFunctionNotDeclaredStaticStorageQuery()))
  }

  Query arrayExternalLinkageSizeExplicitlySpecifiedQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `arrayExternalLinkageSizeExplicitlySpecified` query
      TQueryC(TDeclarations6PackageQuery(TArrayExternalLinkageSizeExplicitlySpecifiedQuery()))
  }

  Query shouldNotBeDefinedWithExternalLinkageQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `shouldNotBeDefinedWithExternalLinkage` query
      TQueryC(TDeclarations6PackageQuery(TShouldNotBeDefinedWithExternalLinkageQuery()))
  }
}
