//** THIS FILE IS AUTOGENERATED, DO NOT MODIFY DIRECTLY.  **/
import cpp
import RuleMetadata
import codingstandards.cpp.exclusions.RuleMetadata

newtype InvalidMemory2Query =
  TVariableLengthArraySizeNotInValidRangeQuery() or
  TDoNotUsePointerArithmeticOnNonArrayObjectPointersQuery() or
  TDoNotModifyObjectsWithTemporaryLifetimeQuery()

predicate isInvalidMemory2QueryMetadata(Query query, string queryId, string ruleId, string category) {
  query =
    // `Query` instance for the `variableLengthArraySizeNotInValidRange` query
    InvalidMemory2Package::variableLengthArraySizeNotInValidRangeQuery() and
  queryId =
    // `@id` for the `variableLengthArraySizeNotInValidRange` query
    "c/cert/variable-length-array-size-not-in-valid-range" and
  ruleId = "ARR32-C" and
  category = "rule"
  or
  query =
    // `Query` instance for the `doNotUsePointerArithmeticOnNonArrayObjectPointers` query
    InvalidMemory2Package::doNotUsePointerArithmeticOnNonArrayObjectPointersQuery() and
  queryId =
    // `@id` for the `doNotUsePointerArithmeticOnNonArrayObjectPointers` query
    "c/cert/do-not-use-pointer-arithmetic-on-non-array-object-pointers" and
  ruleId = "ARR37-C" and
  category = "rule"
  or
  query =
    // `Query` instance for the `doNotModifyObjectsWithTemporaryLifetime` query
    InvalidMemory2Package::doNotModifyObjectsWithTemporaryLifetimeQuery() and
  queryId =
    // `@id` for the `doNotModifyObjectsWithTemporaryLifetime` query
    "c/cert/do-not-modify-objects-with-temporary-lifetime" and
  ruleId = "EXP35-C" and
  category = "rule"
}

module InvalidMemory2Package {
  Query variableLengthArraySizeNotInValidRangeQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `variableLengthArraySizeNotInValidRange` query
      TQueryC(TInvalidMemory2PackageQuery(TVariableLengthArraySizeNotInValidRangeQuery()))
  }

  Query doNotUsePointerArithmeticOnNonArrayObjectPointersQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `doNotUsePointerArithmeticOnNonArrayObjectPointers` query
      TQueryC(TInvalidMemory2PackageQuery(TDoNotUsePointerArithmeticOnNonArrayObjectPointersQuery()))
  }

  Query doNotModifyObjectsWithTemporaryLifetimeQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `doNotModifyObjectsWithTemporaryLifetime` query
      TQueryC(TInvalidMemory2PackageQuery(TDoNotModifyObjectsWithTemporaryLifetimeQuery()))
  }
}
