//** THIS FILE IS AUTOGENERATED, DO NOT MODIFY DIRECTLY.  **/
import cpp
import RuleMetadata
import codingstandards.cpp.exclusions.RuleMetadata

newtype Language4Query =
  TUseOfObsoleteMacroAtomicVarInitQuery() or
  TInvalidDefineOrUndefOfStdBoolMacroQuery() or
  TCallToReallocWithSizeZeroQuery()

predicate isLanguage4QueryMetadata(Query query, string queryId, string ruleId, string category) {
  query =
    // `Query` instance for the `useOfObsoleteMacroAtomicVarInit` query
    Language4Package::useOfObsoleteMacroAtomicVarInitQuery() and
  queryId =
    // `@id` for the `useOfObsoleteMacroAtomicVarInit` query
    "c/misra/use-of-obsolete-macro-atomic-var-init" and
  ruleId = "RULE-1-5" and
  category = "required"
  or
  query =
    // `Query` instance for the `invalidDefineOrUndefOfStdBoolMacro` query
    Language4Package::invalidDefineOrUndefOfStdBoolMacroQuery() and
  queryId =
    // `@id` for the `invalidDefineOrUndefOfStdBoolMacro` query
    "c/misra/invalid-define-or-undef-of-std-bool-macro" and
  ruleId = "RULE-1-5" and
  category = "required"
  or
  query =
    // `Query` instance for the `callToReallocWithSizeZero` query
    Language4Package::callToReallocWithSizeZeroQuery() and
  queryId =
    // `@id` for the `callToReallocWithSizeZero` query
    "c/misra/call-to-realloc-with-size-zero" and
  ruleId = "RULE-1-5" and
  category = "required"
}

module Language4Package {
  Query useOfObsoleteMacroAtomicVarInitQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `useOfObsoleteMacroAtomicVarInit` query
      TQueryC(TLanguage4PackageQuery(TUseOfObsoleteMacroAtomicVarInitQuery()))
  }

  Query invalidDefineOrUndefOfStdBoolMacroQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `invalidDefineOrUndefOfStdBoolMacro` query
      TQueryC(TLanguage4PackageQuery(TInvalidDefineOrUndefOfStdBoolMacroQuery()))
  }

  Query callToReallocWithSizeZeroQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `callToReallocWithSizeZero` query
      TQueryC(TLanguage4PackageQuery(TCallToReallocWithSizeZeroQuery()))
  }
}
