//** THIS FILE IS AUTOGENERATED, DO NOT MODIFY DIRECTLY.  **/
import cpp
import RuleMetadata
import codingstandards.cpp.exclusions.RuleMetadata

newtype Memory1Query =
  TInitializerForAggregateOrUnionNotEnclosedInBracesQuery() or
  TPartiallyInitializedArrayWithExplicitInitializersQuery() or
  TRepeatedInitializationOfAggregateObjectElementQuery()

predicate isMemory1QueryMetadata(Query query, string queryId, string ruleId, string category) {
  query =
    // `Query` instance for the `initializerForAggregateOrUnionNotEnclosedInBraces` query
    Memory1Package::initializerForAggregateOrUnionNotEnclosedInBracesQuery() and
  queryId =
    // `@id` for the `initializerForAggregateOrUnionNotEnclosedInBraces` query
    "c/misra/initializer-for-aggregate-or-union-not-enclosed-in-braces" and
  ruleId = "RULE-9-2" and
  category = "required"
  or
  query =
    // `Query` instance for the `partiallyInitializedArrayWithExplicitInitializers` query
    Memory1Package::partiallyInitializedArrayWithExplicitInitializersQuery() and
  queryId =
    // `@id` for the `partiallyInitializedArrayWithExplicitInitializers` query
    "c/misra/partially-initialized-array-with-explicit-initializers" and
  ruleId = "RULE-9-3" and
  category = "required"
  or
  query =
    // `Query` instance for the `repeatedInitializationOfAggregateObjectElement` query
    Memory1Package::repeatedInitializationOfAggregateObjectElementQuery() and
  queryId =
    // `@id` for the `repeatedInitializationOfAggregateObjectElement` query
    "c/misra/repeated-initialization-of-aggregate-object-element" and
  ruleId = "RULE-9-4" and
  category = "required"
}

module Memory1Package {
  Query initializerForAggregateOrUnionNotEnclosedInBracesQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `initializerForAggregateOrUnionNotEnclosedInBraces` query
      TQueryC(TMemory1PackageQuery(TInitializerForAggregateOrUnionNotEnclosedInBracesQuery()))
  }

  Query partiallyInitializedArrayWithExplicitInitializersQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `partiallyInitializedArrayWithExplicitInitializers` query
      TQueryC(TMemory1PackageQuery(TPartiallyInitializedArrayWithExplicitInitializersQuery()))
  }

  Query repeatedInitializationOfAggregateObjectElementQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `repeatedInitializationOfAggregateObjectElement` query
      TQueryC(TMemory1PackageQuery(TRepeatedInitializationOfAggregateObjectElementQuery()))
  }
}
