//** THIS FILE IS AUTOGENERATED, DO NOT MODIFY DIRECTLY.  **/
import cpp
import RuleMetadata
import codingstandards.cpp.exclusions.RuleMetadata

newtype Memory2Query =
  TDoNotSubtractPointersThatDoNotReferToTheSameArrayQuery() or
  TDoNotRelatePointersThatDoNotReferToTheSameArrayQuery() or
  TDoNotComparePaddingDataQuery() or
  TFreeMemoryWhenNoLongerNeededCertQuery() or
  TAllocStructsWithAFlexibleArrayMemberDynamicallyQuery() or
  TCopyStructsWithAFlexibleArrayMemberDynamicallyQuery() or
  TOnlyFreeMemoryAllocatedDynamicallyCertQuery() or
  TDoNotModifyAlignmentOfMemoryWithReallocQuery() or
  TFreeMemoryWhenNoLongerNeededMisraQuery() or
  TCloseFileHandleWhenNoLongerNeededMisraQuery() or
  TOnlyFreeMemoryAllocatedDynamicallyMisraQuery()

predicate isMemory2QueryMetadata(Query query, string queryId, string ruleId, string category) {
  query =
    // `Query` instance for the `doNotSubtractPointersThatDoNotReferToTheSameArray` query
    Memory2Package::doNotSubtractPointersThatDoNotReferToTheSameArrayQuery() and
  queryId =
    // `@id` for the `doNotSubtractPointersThatDoNotReferToTheSameArray` query
    "c/cert/do-not-subtract-pointers-that-do-not-refer-to-the-same-array" and
  ruleId = "ARR36-C" and
  category = "rule"
  or
  query =
    // `Query` instance for the `doNotRelatePointersThatDoNotReferToTheSameArray` query
    Memory2Package::doNotRelatePointersThatDoNotReferToTheSameArrayQuery() and
  queryId =
    // `@id` for the `doNotRelatePointersThatDoNotReferToTheSameArray` query
    "c/cert/do-not-relate-pointers-that-do-not-refer-to-the-same-array" and
  ruleId = "ARR36-C" and
  category = "rule"
  or
  query =
    // `Query` instance for the `doNotComparePaddingData` query
    Memory2Package::doNotComparePaddingDataQuery() and
  queryId =
    // `@id` for the `doNotComparePaddingData` query
    "c/cert/do-not-compare-padding-data" and
  ruleId = "EXP42-C" and
  category = "rule"
  or
  query =
    // `Query` instance for the `freeMemoryWhenNoLongerNeededCert` query
    Memory2Package::freeMemoryWhenNoLongerNeededCertQuery() and
  queryId =
    // `@id` for the `freeMemoryWhenNoLongerNeededCert` query
    "c/cert/free-memory-when-no-longer-needed-cert" and
  ruleId = "MEM31-C" and
  category = "rule"
  or
  query =
    // `Query` instance for the `allocStructsWithAFlexibleArrayMemberDynamically` query
    Memory2Package::allocStructsWithAFlexibleArrayMemberDynamicallyQuery() and
  queryId =
    // `@id` for the `allocStructsWithAFlexibleArrayMemberDynamically` query
    "c/cert/alloc-structs-with-a-flexible-array-member-dynamically" and
  ruleId = "MEM33-C" and
  category = "rule"
  or
  query =
    // `Query` instance for the `copyStructsWithAFlexibleArrayMemberDynamically` query
    Memory2Package::copyStructsWithAFlexibleArrayMemberDynamicallyQuery() and
  queryId =
    // `@id` for the `copyStructsWithAFlexibleArrayMemberDynamically` query
    "c/cert/copy-structs-with-a-flexible-array-member-dynamically" and
  ruleId = "MEM33-C" and
  category = "rule"
  or
  query =
    // `Query` instance for the `onlyFreeMemoryAllocatedDynamicallyCert` query
    Memory2Package::onlyFreeMemoryAllocatedDynamicallyCertQuery() and
  queryId =
    // `@id` for the `onlyFreeMemoryAllocatedDynamicallyCert` query
    "c/cert/only-free-memory-allocated-dynamically-cert" and
  ruleId = "MEM34-C" and
  category = "rule"
  or
  query =
    // `Query` instance for the `doNotModifyAlignmentOfMemoryWithRealloc` query
    Memory2Package::doNotModifyAlignmentOfMemoryWithReallocQuery() and
  queryId =
    // `@id` for the `doNotModifyAlignmentOfMemoryWithRealloc` query
    "c/cert/do-not-modify-alignment-of-memory-with-realloc" and
  ruleId = "MEM36-C" and
  category = "rule"
  or
  query =
    // `Query` instance for the `freeMemoryWhenNoLongerNeededMisra` query
    Memory2Package::freeMemoryWhenNoLongerNeededMisraQuery() and
  queryId =
    // `@id` for the `freeMemoryWhenNoLongerNeededMisra` query
    "c/misra/free-memory-when-no-longer-needed-misra" and
  ruleId = "RULE-22-1" and
  category = "required"
  or
  query =
    // `Query` instance for the `closeFileHandleWhenNoLongerNeededMisra` query
    Memory2Package::closeFileHandleWhenNoLongerNeededMisraQuery() and
  queryId =
    // `@id` for the `closeFileHandleWhenNoLongerNeededMisra` query
    "c/misra/close-file-handle-when-no-longer-needed-misra" and
  ruleId = "RULE-22-1" and
  category = "required"
  or
  query =
    // `Query` instance for the `onlyFreeMemoryAllocatedDynamicallyMisra` query
    Memory2Package::onlyFreeMemoryAllocatedDynamicallyMisraQuery() and
  queryId =
    // `@id` for the `onlyFreeMemoryAllocatedDynamicallyMisra` query
    "c/misra/only-free-memory-allocated-dynamically-misra" and
  ruleId = "RULE-22-2" and
  category = "mandatory"
}

module Memory2Package {
  Query doNotSubtractPointersThatDoNotReferToTheSameArrayQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `doNotSubtractPointersThatDoNotReferToTheSameArray` query
      TQueryC(TMemory2PackageQuery(TDoNotSubtractPointersThatDoNotReferToTheSameArrayQuery()))
  }

  Query doNotRelatePointersThatDoNotReferToTheSameArrayQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `doNotRelatePointersThatDoNotReferToTheSameArray` query
      TQueryC(TMemory2PackageQuery(TDoNotRelatePointersThatDoNotReferToTheSameArrayQuery()))
  }

  Query doNotComparePaddingDataQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `doNotComparePaddingData` query
      TQueryC(TMemory2PackageQuery(TDoNotComparePaddingDataQuery()))
  }

  Query freeMemoryWhenNoLongerNeededCertQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `freeMemoryWhenNoLongerNeededCert` query
      TQueryC(TMemory2PackageQuery(TFreeMemoryWhenNoLongerNeededCertQuery()))
  }

  Query allocStructsWithAFlexibleArrayMemberDynamicallyQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `allocStructsWithAFlexibleArrayMemberDynamically` query
      TQueryC(TMemory2PackageQuery(TAllocStructsWithAFlexibleArrayMemberDynamicallyQuery()))
  }

  Query copyStructsWithAFlexibleArrayMemberDynamicallyQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `copyStructsWithAFlexibleArrayMemberDynamically` query
      TQueryC(TMemory2PackageQuery(TCopyStructsWithAFlexibleArrayMemberDynamicallyQuery()))
  }

  Query onlyFreeMemoryAllocatedDynamicallyCertQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `onlyFreeMemoryAllocatedDynamicallyCert` query
      TQueryC(TMemory2PackageQuery(TOnlyFreeMemoryAllocatedDynamicallyCertQuery()))
  }

  Query doNotModifyAlignmentOfMemoryWithReallocQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `doNotModifyAlignmentOfMemoryWithRealloc` query
      TQueryC(TMemory2PackageQuery(TDoNotModifyAlignmentOfMemoryWithReallocQuery()))
  }

  Query freeMemoryWhenNoLongerNeededMisraQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `freeMemoryWhenNoLongerNeededMisra` query
      TQueryC(TMemory2PackageQuery(TFreeMemoryWhenNoLongerNeededMisraQuery()))
  }

  Query closeFileHandleWhenNoLongerNeededMisraQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `closeFileHandleWhenNoLongerNeededMisra` query
      TQueryC(TMemory2PackageQuery(TCloseFileHandleWhenNoLongerNeededMisraQuery()))
  }

  Query onlyFreeMemoryAllocatedDynamicallyMisraQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `onlyFreeMemoryAllocatedDynamicallyMisra` query
      TQueryC(TMemory2PackageQuery(TOnlyFreeMemoryAllocatedDynamicallyMisraQuery()))
  }
}
