//** THIS FILE IS AUTOGENERATED, DO NOT MODIFY DIRECTLY.  **/
import cpp
import RuleMetadata
import codingstandards.cpp.exclusions.RuleMetadata

newtype Preprocessor2Query =
  TMoreThanOneHashOperatorInMacroDefinitionQuery() or
  TMacroParameterUsedAsHashOperandQuery() or
  TUndefShouldNotBeUsedQuery() or
  TPrecautionIncludeGuardsNotProvidedQuery()

predicate isPreprocessor2QueryMetadata(Query query, string queryId, string ruleId) {
  query =
    // `Query` instance for the `moreThanOneHashOperatorInMacroDefinition` query
    Preprocessor2Package::moreThanOneHashOperatorInMacroDefinitionQuery() and
  queryId =
    // `@id` for the `moreThanOneHashOperatorInMacroDefinition` query
    "c/misra/more-than-one-hash-operator-in-macro-definition" and
  ruleId = "RULE-20-11"
  or
  query =
    // `Query` instance for the `macroParameterUsedAsHashOperand` query
    Preprocessor2Package::macroParameterUsedAsHashOperandQuery() and
  queryId =
    // `@id` for the `macroParameterUsedAsHashOperand` query
    "c/misra/macro-parameter-used-as-hash-operand" and
  ruleId = "RULE-20-12"
  or
  query =
    // `Query` instance for the `undefShouldNotBeUsed` query
    Preprocessor2Package::undefShouldNotBeUsedQuery() and
  queryId =
    // `@id` for the `undefShouldNotBeUsed` query
    "c/misra/undef-should-not-be-used" and
  ruleId = "RULE-20-5"
  or
  query =
    // `Query` instance for the `precautionIncludeGuardsNotProvided` query
    Preprocessor2Package::precautionIncludeGuardsNotProvidedQuery() and
  queryId =
    // `@id` for the `precautionIncludeGuardsNotProvided` query
    "c/misra/precaution-include-guards-not-provided" and
  ruleId = "RULE-4-10"
}

module Preprocessor2Package {
  Query moreThanOneHashOperatorInMacroDefinitionQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `moreThanOneHashOperatorInMacroDefinition` query
      TQueryC(TPreprocessor2PackageQuery(TMoreThanOneHashOperatorInMacroDefinitionQuery()))
  }

  Query macroParameterUsedAsHashOperandQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `macroParameterUsedAsHashOperand` query
      TQueryC(TPreprocessor2PackageQuery(TMacroParameterUsedAsHashOperandQuery()))
  }

  Query undefShouldNotBeUsedQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `undefShouldNotBeUsed` query
      TQueryC(TPreprocessor2PackageQuery(TUndefShouldNotBeUsedQuery()))
  }

  Query precautionIncludeGuardsNotProvidedQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `precautionIncludeGuardsNotProvided` query
      TQueryC(TPreprocessor2PackageQuery(TPrecautionIncludeGuardsNotProvidedQuery()))
  }
}
