//** THIS FILE IS AUTOGENERATED, DO NOT MODIFY DIRECTLY.  **/
import cpp
import RuleMetadata
import codingstandards.cpp.exclusions.RuleMetadata

newtype Preprocessor5Query = TMacroParameterNotEnclosedInParenthesesCQueryQuery()

predicate isPreprocessor5QueryMetadata(Query query, string queryId, string ruleId) {
  query =
    // `Query` instance for the `macroParameterNotEnclosedInParenthesesCQuery` query
    Preprocessor5Package::macroParameterNotEnclosedInParenthesesCQueryQuery() and
  queryId =
    // `@id` for the `macroParameterNotEnclosedInParenthesesCQuery` query
    "c/misra/macro-parameter-not-enclosed-in-parentheses-c-query" and
  ruleId = "RULE-20-7"
}

module Preprocessor5Package {
  Query macroParameterNotEnclosedInParenthesesCQueryQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `macroParameterNotEnclosedInParenthesesCQuery` query
      TQueryC(TPreprocessor5PackageQuery(TMacroParameterNotEnclosedInParenthesesCQueryQuery()))
  }
}
