//** THIS FILE IS AUTOGENERATED, DO NOT MODIFY DIRECTLY.  **/
import cpp
import RuleMetadata
import codingstandards.cpp.exclusions.RuleMetadata

newtype Preprocessor5Query =
  TDoNotTreatAPredefinedIdentifierAsObjectQuery() or
  TMacroOrFunctionArgsContainHashTokenQuery() or
  TMacroParameterNotEnclosedInParenthesesCQueryQuery()

predicate isPreprocessor5QueryMetadata(Query query, string queryId, string ruleId, string category) {
  query =
    // `Query` instance for the `doNotTreatAPredefinedIdentifierAsObject` query
    Preprocessor5Package::doNotTreatAPredefinedIdentifierAsObjectQuery() and
  queryId =
    // `@id` for the `doNotTreatAPredefinedIdentifierAsObject` query
    "c/cert/do-not-treat-a-predefined-identifier-as-object" and
  ruleId = "MSC38-C" and
  category = "rule"
  or
  query =
    // `Query` instance for the `macroOrFunctionArgsContainHashToken` query
    Preprocessor5Package::macroOrFunctionArgsContainHashTokenQuery() and
  queryId =
    // `@id` for the `macroOrFunctionArgsContainHashToken` query
    "c/cert/macro-or-function-args-contain-hash-token" and
  ruleId = "PRE32-C" and
  category = "rule"
  or
  query =
    // `Query` instance for the `macroParameterNotEnclosedInParenthesesCQuery` query
    Preprocessor5Package::macroParameterNotEnclosedInParenthesesCQueryQuery() and
  queryId =
    // `@id` for the `macroParameterNotEnclosedInParenthesesCQuery` query
    "c/misra/macro-parameter-not-enclosed-in-parentheses-c-query" and
  ruleId = "RULE-20-7" and
  category = "required"
}

module Preprocessor5Package {
  Query doNotTreatAPredefinedIdentifierAsObjectQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `doNotTreatAPredefinedIdentifierAsObject` query
      TQueryC(TPreprocessor5PackageQuery(TDoNotTreatAPredefinedIdentifierAsObjectQuery()))
  }

  Query macroOrFunctionArgsContainHashTokenQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `macroOrFunctionArgsContainHashToken` query
      TQueryC(TPreprocessor5PackageQuery(TMacroOrFunctionArgsContainHashTokenQuery()))
  }

  Query macroParameterNotEnclosedInParenthesesCQueryQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `macroParameterNotEnclosedInParenthesesCQuery` query
      TQueryC(TPreprocessor5PackageQuery(TMacroParameterNotEnclosedInParenthesesCQueryQuery()))
  }
}
