//** THIS FILE IS AUTOGENERATED, DO NOT MODIFY DIRECTLY.  **/
import cpp
import codingstandards.cpp.exclusions.RuleMetadata
//** Import packages for this language **/
import IO1
import IO2
import IO3
import Misc
import Preprocessor1
import Preprocessor2
import SideEffects1
import SideEffects2
import Strings1
import Strings2
import Syntax

/** The TQuery type representing this language * */
newtype TCQuery =
  TIO1PackageQuery(IO1Query q) or
  TIO2PackageQuery(IO2Query q) or
  TIO3PackageQuery(IO3Query q) or
  TMiscPackageQuery(MiscQuery q) or
  TPreprocessor1PackageQuery(Preprocessor1Query q) or
  TPreprocessor2PackageQuery(Preprocessor2Query q) or
  TSideEffects1PackageQuery(SideEffects1Query q) or
  TSideEffects2PackageQuery(SideEffects2Query q) or
  TStrings1PackageQuery(Strings1Query q) or
  TStrings2PackageQuery(Strings2Query q) or
  TSyntaxPackageQuery(SyntaxQuery q)

/** The metadata predicate * */
predicate isQueryMetadata(Query query, string queryId, string ruleId) {
  isIO1QueryMetadata(query, queryId, ruleId) or
  isIO2QueryMetadata(query, queryId, ruleId) or
  isIO3QueryMetadata(query, queryId, ruleId) or
  isMiscQueryMetadata(query, queryId, ruleId) or
  isPreprocessor1QueryMetadata(query, queryId, ruleId) or
  isPreprocessor2QueryMetadata(query, queryId, ruleId) or
  isSideEffects1QueryMetadata(query, queryId, ruleId) or
  isSideEffects2QueryMetadata(query, queryId, ruleId) or
  isStrings1QueryMetadata(query, queryId, ruleId) or
  isStrings2QueryMetadata(query, queryId, ruleId) or
  isSyntaxQueryMetadata(query, queryId, ruleId)
}
