//** THIS FILE IS AUTOGENERATED, DO NOT MODIFY DIRECTLY.  **/
import cpp
import RuleMetadata
import codingstandards.cpp.exclusions.RuleMetadata

newtype Statements6Query = TGotoStatementUsedQuery()

predicate isStatements6QueryMetadata(Query query, string queryId, string ruleId, string category) {
  query =
    // `Query` instance for the `gotoStatementUsed` query
    Statements6Package::gotoStatementUsedQuery() and
  queryId =
    // `@id` for the `gotoStatementUsed` query
    "c/misra/goto-statement-used" and
  ruleId = "RULE-15-1" and
  category = "advisory"
}

module Statements6Package {
  Query gotoStatementUsedQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `gotoStatementUsed` query
      TQueryC(TStatements6PackageQuery(TGotoStatementUsedQuery()))
  }
}
