//** THIS FILE IS AUTOGENERATED, DO NOT MODIFY DIRECTLY.  **/
import cpp
import RuleMetadata
import codingstandards.cpp.exclusions.RuleMetadata

newtype Statements1Query =
  TNestSwitchLabelInSwitchStatementQuery() or
  TBreakShallTerminateSwitchClauseQuery() or
  TEverySwitchShallHaveDefaultLabelQuery() or
  TDefaultNotFirstOrLastOfSwitchQuery()

predicate isStatements1QueryMetadata(Query query, string queryId, string ruleId, string category) {
  query =
    // `Query` instance for the `nestSwitchLabelInSwitchStatement` query
    Statements1Package::nestSwitchLabelInSwitchStatementQuery() and
  queryId =
    // `@id` for the `nestSwitchLabelInSwitchStatement` query
    "c/misra/nest-switch-label-in-switch-statement" and
  ruleId = "RULE-16-2" and
  category = "required"
  or
  query =
    // `Query` instance for the `breakShallTerminateSwitchClause` query
    Statements1Package::breakShallTerminateSwitchClauseQuery() and
  queryId =
    // `@id` for the `breakShallTerminateSwitchClause` query
    "c/misra/break-shall-terminate-switch-clause" and
  ruleId = "RULE-16-3" and
  category = "required"
  or
  query =
    // `Query` instance for the `everySwitchShallHaveDefaultLabel` query
    Statements1Package::everySwitchShallHaveDefaultLabelQuery() and
  queryId =
    // `@id` for the `everySwitchShallHaveDefaultLabel` query
    "c/misra/every-switch-shall-have-default-label" and
  ruleId = "RULE-16-4" and
  category = "required"
  or
  query =
    // `Query` instance for the `defaultNotFirstOrLastOfSwitch` query
    Statements1Package::defaultNotFirstOrLastOfSwitchQuery() and
  queryId =
    // `@id` for the `defaultNotFirstOrLastOfSwitch` query
    "c/misra/default-not-first-or-last-of-switch" and
  ruleId = "RULE-16-5" and
  category = "required"
}

module Statements1Package {
  Query nestSwitchLabelInSwitchStatementQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `nestSwitchLabelInSwitchStatement` query
      TQueryC(TStatements1PackageQuery(TNestSwitchLabelInSwitchStatementQuery()))
  }

  Query breakShallTerminateSwitchClauseQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `breakShallTerminateSwitchClause` query
      TQueryC(TStatements1PackageQuery(TBreakShallTerminateSwitchClauseQuery()))
  }

  Query everySwitchShallHaveDefaultLabelQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `everySwitchShallHaveDefaultLabel` query
      TQueryC(TStatements1PackageQuery(TEverySwitchShallHaveDefaultLabelQuery()))
  }

  Query defaultNotFirstOrLastOfSwitchQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `defaultNotFirstOrLastOfSwitch` query
      TQueryC(TStatements1PackageQuery(TDefaultNotFirstOrLastOfSwitchQuery()))
  }
}
