//** THIS FILE IS AUTOGENERATED, DO NOT MODIFY DIRECTLY.  **/
import cpp
import RuleMetadata
import codingstandards.cpp.exclusions.RuleMetadata

newtype Statements5Query =
  TControllingExprInvariantQuery() or
  TFunctionReturnConditionQuery() or
  TNonVoidFunctionReturnConditionQuery()

predicate isStatements5QueryMetadata(Query query, string queryId, string ruleId, string category) {
  query =
    // `Query` instance for the `controllingExprInvariant` query
    Statements5Package::controllingExprInvariantQuery() and
  queryId =
    // `@id` for the `controllingExprInvariant` query
    "c/misra/controlling-expr-invariant" and
  ruleId = "RULE-14-3" and
  category = "required"
  or
  query =
    // `Query` instance for the `functionReturnCondition` query
    Statements5Package::functionReturnConditionQuery() and
  queryId =
    // `@id` for the `functionReturnCondition` query
    "c/misra/function-return-condition" and
  ruleId = "RULE-15-5" and
  category = "advisory"
  or
  query =
    // `Query` instance for the `nonVoidFunctionReturnCondition` query
    Statements5Package::nonVoidFunctionReturnConditionQuery() and
  queryId =
    // `@id` for the `nonVoidFunctionReturnCondition` query
    "c/misra/non-void-function-return-condition" and
  ruleId = "RULE-17-4" and
  category = "mandatory"
}

module Statements5Package {
  Query controllingExprInvariantQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `controllingExprInvariant` query
      TQueryC(TStatements5PackageQuery(TControllingExprInvariantQuery()))
  }

  Query functionReturnConditionQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `functionReturnCondition` query
      TQueryC(TStatements5PackageQuery(TFunctionReturnConditionQuery()))
  }

  Query nonVoidFunctionReturnConditionQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `nonVoidFunctionReturnCondition` query
      TQueryC(TStatements5PackageQuery(TNonVoidFunctionReturnConditionQuery()))
  }
}
