//** THIS FILE IS AUTOGENERATED, DO NOT MODIFY DIRECTLY.  **/
import cpp
import RuleMetadata
import codingstandards.cpp.exclusions.RuleMetadata

newtype Types1Query =
  TExprShiftedbyNegativeOrGreaterPrecisionOperandQuery() or
  TConvertingAPointerToIntegerOrIntegerToPointerQuery() or
  TPlainNumericalTypeUsedOverExplicitTypedefQuery() or
  TSizeofOperatorUsedOnArrayTypeParamQuery() or
  TStringLiteralAssignedToNonConstCharQuery()

predicate isTypes1QueryMetadata(Query query, string queryId, string ruleId, string category) {
  query =
    // `Query` instance for the `exprShiftedbyNegativeOrGreaterPrecisionOperand` query
    Types1Package::exprShiftedbyNegativeOrGreaterPrecisionOperandQuery() and
  queryId =
    // `@id` for the `exprShiftedbyNegativeOrGreaterPrecisionOperand` query
    "c/cert/expr-shiftedby-negative-or-greater-precision-operand" and
  ruleId = "INT34-C" and
  category = "rule"
  or
  query =
    // `Query` instance for the `convertingAPointerToIntegerOrIntegerToPointer` query
    Types1Package::convertingAPointerToIntegerOrIntegerToPointerQuery() and
  queryId =
    // `@id` for the `convertingAPointerToIntegerOrIntegerToPointer` query
    "c/cert/converting-a-pointer-to-integer-or-integer-to-pointer" and
  ruleId = "INT36-C" and
  category = "rule"
  or
  query =
    // `Query` instance for the `plainNumericalTypeUsedOverExplicitTypedef` query
    Types1Package::plainNumericalTypeUsedOverExplicitTypedefQuery() and
  queryId =
    // `@id` for the `plainNumericalTypeUsedOverExplicitTypedef` query
    "c/misra/plain-numerical-type-used-over-explicit-typedef" and
  ruleId = "DIR-4-6" and
  category = "advisory"
  or
  query =
    // `Query` instance for the `sizeofOperatorUsedOnArrayTypeParam` query
    Types1Package::sizeofOperatorUsedOnArrayTypeParamQuery() and
  queryId =
    // `@id` for the `sizeofOperatorUsedOnArrayTypeParam` query
    "c/misra/sizeof-operator-used-on-array-type-param" and
  ruleId = "RULE-12-5" and
  category = "mandatory"
  or
  query =
    // `Query` instance for the `stringLiteralAssignedToNonConstChar` query
    Types1Package::stringLiteralAssignedToNonConstCharQuery() and
  queryId =
    // `@id` for the `stringLiteralAssignedToNonConstChar` query
    "c/misra/string-literal-assigned-to-non-const-char" and
  ruleId = "RULE-7-4" and
  category = "required"
}

module Types1Package {
  Query exprShiftedbyNegativeOrGreaterPrecisionOperandQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `exprShiftedbyNegativeOrGreaterPrecisionOperand` query
      TQueryC(TTypes1PackageQuery(TExprShiftedbyNegativeOrGreaterPrecisionOperandQuery()))
  }

  Query convertingAPointerToIntegerOrIntegerToPointerQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `convertingAPointerToIntegerOrIntegerToPointer` query
      TQueryC(TTypes1PackageQuery(TConvertingAPointerToIntegerOrIntegerToPointerQuery()))
  }

  Query plainNumericalTypeUsedOverExplicitTypedefQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `plainNumericalTypeUsedOverExplicitTypedef` query
      TQueryC(TTypes1PackageQuery(TPlainNumericalTypeUsedOverExplicitTypedefQuery()))
  }

  Query sizeofOperatorUsedOnArrayTypeParamQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `sizeofOperatorUsedOnArrayTypeParam` query
      TQueryC(TTypes1PackageQuery(TSizeofOperatorUsedOnArrayTypeParamQuery()))
  }

  Query stringLiteralAssignedToNonConstCharQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `stringLiteralAssignedToNonConstChar` query
      TQueryC(TTypes1PackageQuery(TStringLiteralAssignedToNonConstCharQuery()))
  }
}
