//** THIS FILE IS AUTOGENERATED, DO NOT MODIFY DIRECTLY.  **/
import cpp
import RuleMetadata
import codingstandards.cpp.exclusions.RuleMetadata

newtype Types2Query =
  TInvalidIntegerConstantMacroArgumentQuery() or
  TUseOfBannedSmallIntegerConstantMacroQuery()

predicate isTypes2QueryMetadata(Query query, string queryId, string ruleId, string category) {
  query =
    // `Query` instance for the `invalidIntegerConstantMacroArgument` query
    Types2Package::invalidIntegerConstantMacroArgumentQuery() and
  queryId =
    // `@id` for the `invalidIntegerConstantMacroArgument` query
    "c/misra/invalid-integer-constant-macro-argument" and
  ruleId = "RULE-7-5" and
  category = "required"
  or
  query =
    // `Query` instance for the `useOfBannedSmallIntegerConstantMacro` query
    Types2Package::useOfBannedSmallIntegerConstantMacroQuery() and
  queryId =
    // `@id` for the `useOfBannedSmallIntegerConstantMacro` query
    "c/misra/use-of-banned-small-integer-constant-macro" and
  ruleId = "RULE-7-6" and
  category = "required"
}

module Types2Package {
  Query invalidIntegerConstantMacroArgumentQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `invalidIntegerConstantMacroArgument` query
      TQueryC(TTypes2PackageQuery(TInvalidIntegerConstantMacroArgumentQuery()))
  }

  Query useOfBannedSmallIntegerConstantMacroQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `useOfBannedSmallIntegerConstantMacro` query
      TQueryC(TTypes2PackageQuery(TUseOfBannedSmallIntegerConstantMacroQuery()))
  }
}
