#include <assert.h>   // NON_COMPLIANT
#include <ctype.h>    // NON_COMPLIANT
#include <errno.h>    // NON_COMPLIANT
#include <fenv.h>     // NON_COMPLIANT
#include <float.h>    // NON_COMPLIANT
#include <inttypes.h> // NON_COMPLIANT
#include <limits.h>   // NON_COMPLIANT
#include <locale.h>   // NON_COMPLIANT
#include <math.h>     // NON_COMPLIANT
#include <setjmp.h>   // NON_COMPLIANT
#include <signal.h>   // NON_COMPLIANT
#include <stdarg.h>   // NON_COMPLIANT
#include <stddef.h>   // NON_COMPLIANT
#include <stdint.h>   // NON_COMPLIANT
#include <stdio.h>    // NON_COMPLIANT
#include <stdlib.h>   // NON_COMPLIANT
#include <string.h>   // NON_COMPLIANT
#include <time.h>     // NON_COMPLIANT
#include <uchar.h>    // NON_COMPLIANT
#include <wchar.h>    // NON_COMPLIANT
#include <wctype.h>   // NON_COMPLIANT

#include <cassert>   // COMPLIANT
#include <cctype>    // COMPLIANT
#include <cerrno>    // COMPLIANT
#include <cfenv>     // COMPLIANT
#include <cfloat>    // COMPLIANT
#include <cinttypes> // COMPLIANT
#include <climits>   // COMPLIANT
#include <clocale>   // COMPLIANT
#include <cmath>     // COMPLIANT
#include <csetjmp>   // COMPLIANT
#include <csignal>   // COMPLIANT
#include <cstdarg>   // COMPLIANT
#include <cstddef>   // COMPLIANT
#include <cstdint>   // COMPLIANT
#include <cstdlib>   // COMPLIANT
#include <cstring>   // COMPLIANT
#include <ctime>     // COMPLIANT
#include <cuchar>    // COMPLIANT
#include <cwchar>    // COMPLIANT
#include <cwctype>   // COMPLIANT