//** THIS FILE IS AUTOGENERATED, DO NOT MODIFY DIRECTLY.  **/
import cpp
import RuleMetadata
import codingstandards.cpp.exclusions.RuleMetadata

newtype Banned1Query = TGlobalVariableUsedQuery()

predicate isBanned1QueryMetadata(Query query, string queryId, string ruleId, string category) {
  query =
    // `Query` instance for the `globalVariableUsed` query
    Banned1Package::globalVariableUsedQuery() and
  queryId =
    // `@id` for the `globalVariableUsed` query
    "cpp/misra/global-variable-used" and
  ruleId = "RULE-6-7-2" and
  category = "required"
}

module Banned1Package {
  Query globalVariableUsedQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `globalVariableUsed` query
      TQueryCPP(TBanned1PackageQuery(TGlobalVariableUsedQuery()))
  }
}
