//** THIS FILE IS AUTOGENERATED, DO NOT MODIFY DIRECTLY.  **/
import cpp
import RuleMetadata
import codingstandards.cpp.exclusions.RuleMetadata

newtype Banned5Query = TBitFieldsShouldNotBeDeclaredQuery()

predicate isBanned5QueryMetadata(Query query, string queryId, string ruleId, string category) {
  query =
    // `Query` instance for the `bitFieldsShouldNotBeDeclared` query
    Banned5Package::bitFieldsShouldNotBeDeclaredQuery() and
  queryId =
    // `@id` for the `bitFieldsShouldNotBeDeclared` query
    "cpp/misra/bit-fields-should-not-be-declared" and
  ruleId = "RULE-12-2-1" and
  category = "advisory"
}

module Banned5Package {
  Query bitFieldsShouldNotBeDeclaredQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `bitFieldsShouldNotBeDeclared` query
      TQueryCPP(TBanned5PackageQuery(TBitFieldsShouldNotBeDeclaredQuery()))
  }
}
