//** THIS FILE IS AUTOGENERATED, DO NOT MODIFY DIRECTLY.  **/
import cpp
import RuleMetadata
import codingstandards.cpp.exclusions.RuleMetadata

newtype Banned6Query = TUnionKeywordUsedMisraCppQuery()

predicate isBanned6QueryMetadata(Query query, string queryId, string ruleId, string category) {
  query =
    // `Query` instance for the `unionKeywordUsedMisraCpp` query
    Banned6Package::unionKeywordUsedMisraCppQuery() and
  queryId =
    // `@id` for the `unionKeywordUsedMisraCpp` query
    "cpp/misra/union-keyword-used-misra-cpp" and
  ruleId = "RULE-12-3-1" and
  category = "required"
}

module Banned6Package {
  Query unionKeywordUsedMisraCppQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `unionKeywordUsedMisraCpp` query
      TQueryCPP(TBanned6PackageQuery(TUnionKeywordUsedMisraCppQuery()))
  }
}
