//** THIS FILE IS AUTOGENERATED, DO NOT MODIFY DIRECTLY.  **/
import cpp
import RuleMetadata
import codingstandards.cpp.exclusions.RuleMetadata

newtype Banned7Query = TDynamicMemoryShouldNotBeUsedQuery()

predicate isBanned7QueryMetadata(Query query, string queryId, string ruleId, string category) {
  query =
    // `Query` instance for the `dynamicMemoryShouldNotBeUsed` query
    Banned7Package::dynamicMemoryShouldNotBeUsedQuery() and
  queryId =
    // `@id` for the `dynamicMemoryShouldNotBeUsed` query
    "cpp/misra/dynamic-memory-should-not-be-used" and
  ruleId = "RULE-21-6-1" and
  category = "advisory"
}

module Banned7Package {
  Query dynamicMemoryShouldNotBeUsedQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `dynamicMemoryShouldNotBeUsed` query
      TQueryCPP(TBanned7PackageQuery(TDynamicMemoryShouldNotBeUsedQuery()))
  }
}
