//** THIS FILE IS AUTOGENERATED, DO NOT MODIFY DIRECTLY.  **/
import cpp
import RuleMetadata
import codingstandards.cpp.exclusions.RuleMetadata

newtype Banned8Query = TBuiltInUnaryPlusOperatorShouldNotBeUsedQuery()

predicate isBanned8QueryMetadata(Query query, string queryId, string ruleId, string category) {
  query =
    // `Query` instance for the `builtInUnaryPlusOperatorShouldNotBeUsed` query
    Banned8Package::builtInUnaryPlusOperatorShouldNotBeUsedQuery() and
  queryId =
    // `@id` for the `builtInUnaryPlusOperatorShouldNotBeUsed` query
    "cpp/misra/built-in-unary-plus-operator-should-not-be-used" and
  ruleId = "RULE-8-3-2" and
  category = "advisory"
}

module Banned8Package {
  Query builtInUnaryPlusOperatorShouldNotBeUsedQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `builtInUnaryPlusOperatorShouldNotBeUsed` query
      TQueryCPP(TBanned8PackageQuery(TBuiltInUnaryPlusOperatorShouldNotBeUsedQuery()))
  }
}
