//** THIS FILE IS AUTOGENERATED, DO NOT MODIFY DIRECTLY.  **/
import cpp
import RuleMetadata
import codingstandards.cpp.exclusions.RuleMetadata

newtype Banned6Query = TUnionKeywordUsedQuery()

predicate isBanned6QueryMetadata(Query query, string queryId, string ruleId, string category) {
  query =
    // `Query` instance for the `unionKeywordUsed` query
    Banned6Package::unionKeywordUsedQuery() and
  queryId =
    // `@id` for the `unionKeywordUsed` query
    "cpp/misra/union-keyword-used" and
  ruleId = "RULE-12-3-1" and
  category = "required"
}

module Banned6Package {
  Query unionKeywordUsedQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `unionKeywordUsed` query
      TQueryCPP(TBanned6PackageQuery(TUnionKeywordUsedQuery()))
  }
}
