//** THIS FILE IS AUTOGENERATED, DO NOT MODIFY DIRECTLY.  **/
import cpp
import RuleMetadata
import codingstandards.cpp.exclusions.RuleMetadata

newtype Classes3Query =
  TImproperlyProvidedSpecialMemberFunctionsQuery() or
  TImproperlyProvidedSpecialMemberFunctionsAuditQuery()

predicate isClasses3QueryMetadata(Query query, string queryId, string ruleId, string category) {
  query =
    // `Query` instance for the `improperlyProvidedSpecialMemberFunctions` query
    Classes3Package::improperlyProvidedSpecialMemberFunctionsQuery() and
  queryId =
    // `@id` for the `improperlyProvidedSpecialMemberFunctions` query
    "cpp/misra/improperly-provided-special-member-functions" and
  ruleId = "RULE-15-0-1" and
  category = "required"
  or
  query =
    // `Query` instance for the `improperlyProvidedSpecialMemberFunctionsAudit` query
    Classes3Package::improperlyProvidedSpecialMemberFunctionsAuditQuery() and
  queryId =
    // `@id` for the `improperlyProvidedSpecialMemberFunctionsAudit` query
    "cpp/misra/improperly-provided-special-member-functions-audit" and
  ruleId = "RULE-15-0-1" and
  category = "required"
}

module Classes3Package {
  Query improperlyProvidedSpecialMemberFunctionsQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `improperlyProvidedSpecialMemberFunctions` query
      TQueryCPP(TClasses3PackageQuery(TImproperlyProvidedSpecialMemberFunctionsQuery()))
  }

  Query improperlyProvidedSpecialMemberFunctionsAuditQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `improperlyProvidedSpecialMemberFunctionsAudit` query
      TQueryCPP(TClasses3PackageQuery(TImproperlyProvidedSpecialMemberFunctionsAuditQuery()))
  }
}
