//** THIS FILE IS AUTOGENERATED, DO NOT MODIFY DIRECTLY.  **/
import cpp
import RuleMetadata
import codingstandards.cpp.exclusions.RuleMetadata

newtype ConversionsQuery =
  TNoConversionFromBoolQuery() or
  TNoImplicitBoolConversionQuery() or
  TNoCharacterNumericalValueQuery() or
  TNoSignednessChangeFromPromotionQuery() or
  TNumericAssignmentTypeMismatchQuery() or
  TFunctionPointerConversionContextQuery() or
  TVirtualBaseClassCastToDerivedQuery() or
  TNoCStyleOrFunctionalCastsQuery() or
  TIntToPointerCastProhibitedQuery() or
  TNoPointerToIntegralCastQuery() or
  TPointerToIntegralCastQuery() or
  TNoStandaloneTypeCastExpressionQuery()

predicate isConversionsQueryMetadata(Query query, string queryId, string ruleId, string category) {
  query =
    // `Query` instance for the `noConversionFromBool` query
    ConversionsPackage::noConversionFromBoolQuery() and
  queryId =
    // `@id` for the `noConversionFromBool` query
    "cpp/misra/no-conversion-from-bool" and
  ruleId = "RULE-7-0-1" and
  category = "required"
  or
  query =
    // `Query` instance for the `noImplicitBoolConversion` query
    ConversionsPackage::noImplicitBoolConversionQuery() and
  queryId =
    // `@id` for the `noImplicitBoolConversion` query
    "cpp/misra/no-implicit-bool-conversion" and
  ruleId = "RULE-7-0-2" and
  category = "required"
  or
  query =
    // `Query` instance for the `noCharacterNumericalValue` query
    ConversionsPackage::noCharacterNumericalValueQuery() and
  queryId =
    // `@id` for the `noCharacterNumericalValue` query
    "cpp/misra/no-character-numerical-value" and
  ruleId = "RULE-7-0-3" and
  category = "required"
  or
  query =
    // `Query` instance for the `noSignednessChangeFromPromotion` query
    ConversionsPackage::noSignednessChangeFromPromotionQuery() and
  queryId =
    // `@id` for the `noSignednessChangeFromPromotion` query
    "cpp/misra/no-signedness-change-from-promotion" and
  ruleId = "RULE-7-0-5" and
  category = "required"
  or
  query =
    // `Query` instance for the `numericAssignmentTypeMismatch` query
    ConversionsPackage::numericAssignmentTypeMismatchQuery() and
  queryId =
    // `@id` for the `numericAssignmentTypeMismatch` query
    "cpp/misra/numeric-assignment-type-mismatch" and
  ruleId = "RULE-7-0-6" and
  category = "required"
  or
  query =
    // `Query` instance for the `functionPointerConversionContext` query
    ConversionsPackage::functionPointerConversionContextQuery() and
  queryId =
    // `@id` for the `functionPointerConversionContext` query
    "cpp/misra/function-pointer-conversion-context" and
  ruleId = "RULE-7-11-3" and
  category = "required"
  or
  query =
    // `Query` instance for the `virtualBaseClassCastToDerived` query
    ConversionsPackage::virtualBaseClassCastToDerivedQuery() and
  queryId =
    // `@id` for the `virtualBaseClassCastToDerived` query
    "cpp/misra/virtual-base-class-cast-to-derived" and
  ruleId = "RULE-8-2-1" and
  category = "required"
  or
  query =
    // `Query` instance for the `noCStyleOrFunctionalCasts` query
    ConversionsPackage::noCStyleOrFunctionalCastsQuery() and
  queryId =
    // `@id` for the `noCStyleOrFunctionalCasts` query
    "cpp/misra/no-c-style-or-functional-casts" and
  ruleId = "RULE-8-2-2" and
  category = "required"
  or
  query =
    // `Query` instance for the `intToPointerCastProhibited` query
    ConversionsPackage::intToPointerCastProhibitedQuery() and
  queryId =
    // `@id` for the `intToPointerCastProhibited` query
    "cpp/misra/int-to-pointer-cast-prohibited" and
  ruleId = "RULE-8-2-6" and
  category = "required"
  or
  query =
    // `Query` instance for the `noPointerToIntegralCast` query
    ConversionsPackage::noPointerToIntegralCastQuery() and
  queryId =
    // `@id` for the `noPointerToIntegralCast` query
    "cpp/misra/no-pointer-to-integral-cast" and
  ruleId = "RULE-8-2-7" and
  category = "advisory"
  or
  query =
    // `Query` instance for the `pointerToIntegralCast` query
    ConversionsPackage::pointerToIntegralCastQuery() and
  queryId =
    // `@id` for the `pointerToIntegralCast` query
    "cpp/misra/pointer-to-integral-cast" and
  ruleId = "RULE-8-2-8" and
  category = "required"
  or
  query =
    // `Query` instance for the `noStandaloneTypeCastExpression` query
    ConversionsPackage::noStandaloneTypeCastExpressionQuery() and
  queryId =
    // `@id` for the `noStandaloneTypeCastExpression` query
    "cpp/misra/no-standalone-type-cast-expression" and
  ruleId = "RULE-9-2-1" and
  category = "required"
}

module ConversionsPackage {
  Query noConversionFromBoolQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `noConversionFromBool` query
      TQueryCPP(TConversionsPackageQuery(TNoConversionFromBoolQuery()))
  }

  Query noImplicitBoolConversionQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `noImplicitBoolConversion` query
      TQueryCPP(TConversionsPackageQuery(TNoImplicitBoolConversionQuery()))
  }

  Query noCharacterNumericalValueQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `noCharacterNumericalValue` query
      TQueryCPP(TConversionsPackageQuery(TNoCharacterNumericalValueQuery()))
  }

  Query noSignednessChangeFromPromotionQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `noSignednessChangeFromPromotion` query
      TQueryCPP(TConversionsPackageQuery(TNoSignednessChangeFromPromotionQuery()))
  }

  Query numericAssignmentTypeMismatchQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `numericAssignmentTypeMismatch` query
      TQueryCPP(TConversionsPackageQuery(TNumericAssignmentTypeMismatchQuery()))
  }

  Query functionPointerConversionContextQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `functionPointerConversionContext` query
      TQueryCPP(TConversionsPackageQuery(TFunctionPointerConversionContextQuery()))
  }

  Query virtualBaseClassCastToDerivedQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `virtualBaseClassCastToDerived` query
      TQueryCPP(TConversionsPackageQuery(TVirtualBaseClassCastToDerivedQuery()))
  }

  Query noCStyleOrFunctionalCastsQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `noCStyleOrFunctionalCasts` query
      TQueryCPP(TConversionsPackageQuery(TNoCStyleOrFunctionalCastsQuery()))
  }

  Query intToPointerCastProhibitedQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `intToPointerCastProhibited` query
      TQueryCPP(TConversionsPackageQuery(TIntToPointerCastProhibitedQuery()))
  }

  Query noPointerToIntegralCastQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `noPointerToIntegralCast` query
      TQueryCPP(TConversionsPackageQuery(TNoPointerToIntegralCastQuery()))
  }

  Query pointerToIntegralCastQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `pointerToIntegralCast` query
      TQueryCPP(TConversionsPackageQuery(TPointerToIntegralCastQuery()))
  }

  Query noStandaloneTypeCastExpressionQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `noStandaloneTypeCastExpression` query
      TQueryCPP(TConversionsPackageQuery(TNoStandaloneTypeCastExpressionQuery()))
  }
}
