//** THIS FILE IS AUTOGENERATED, DO NOT MODIFY DIRECTLY.  **/
import cpp
import RuleMetadata
import codingstandards.cpp.exclusions.RuleMetadata

newtype DeadCode11Query = TPotentiallyErroneousContainerUsageQuery()

predicate isDeadCode11QueryMetadata(Query query, string queryId, string ruleId, string category) {
  query =
    // `Query` instance for the `potentiallyErroneousContainerUsage` query
    DeadCode11Package::potentiallyErroneousContainerUsageQuery() and
  queryId =
    // `@id` for the `potentiallyErroneousContainerUsage` query
    "cpp/misra/potentially-erroneous-container-usage" and
  ruleId = "RULE-28-6-4" and
  category = "required"
}

module DeadCode11Package {
  Query potentiallyErroneousContainerUsageQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `potentiallyErroneousContainerUsage` query
      TQueryCPP(TDeadCode11PackageQuery(TPotentiallyErroneousContainerUsageQuery()))
  }
}
