//** THIS FILE IS AUTOGENERATED, DO NOT MODIFY DIRECTLY.  **/
import cpp
import RuleMetadata
import codingstandards.cpp.exclusions.RuleMetadata

newtype DeadCode4Query = TInvariantConditionQuery()

predicate isDeadCode4QueryMetadata(Query query, string queryId, string ruleId, string category) {
  query =
    // `Query` instance for the `invariantCondition` query
    DeadCode4Package::invariantConditionQuery() and
  queryId =
    // `@id` for the `invariantCondition` query
    "cpp/misra/invariant-condition" and
  ruleId = "RULE-0-0-2" and
  category = "advisory"
}

module DeadCode4Package {
  Query invariantConditionQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `invariantCondition` query
      TQueryCPP(TDeadCode4PackageQuery(TInvariantConditionQuery()))
  }
}
