//** THIS FILE IS AUTOGENERATED, DO NOT MODIFY DIRECTLY.  **/
import cpp
import RuleMetadata
import codingstandards.cpp.exclusions.RuleMetadata

newtype DeadCode6Query = TUnusedReturnValueMisraCppQuery()

predicate isDeadCode6QueryMetadata(Query query, string queryId, string ruleId, string category) {
  query =
    // `Query` instance for the `unusedReturnValueMisraCpp` query
    DeadCode6Package::unusedReturnValueMisraCppQuery() and
  queryId =
    // `@id` for the `unusedReturnValueMisraCpp` query
    "cpp/misra/unused-return-value-misra-cpp" and
  ruleId = "RULE-0-1-2" and
  category = "required"
}

module DeadCode6Package {
  Query unusedReturnValueMisraCppQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `unusedReturnValueMisraCpp` query
      TQueryCPP(TDeadCode6PackageQuery(TUnusedReturnValueMisraCppQuery()))
  }
}
