//** THIS FILE IS AUTOGENERATED, DO NOT MODIFY DIRECTLY.  **/
import cpp
import RuleMetadata
import codingstandards.cpp.exclusions.RuleMetadata

newtype Declarations1Query = TDeclarationsOfAFunctionSameParameterNameQuery()

predicate isDeclarations1QueryMetadata(Query query, string queryId, string ruleId, string category) {
  query =
    // `Query` instance for the `declarationsOfAFunctionSameParameterName` query
    Declarations1Package::declarationsOfAFunctionSameParameterNameQuery() and
  queryId =
    // `@id` for the `declarationsOfAFunctionSameParameterName` query
    "cpp/misra/declarations-of-a-function-same-parameter-name" and
  ruleId = "RULE-13-3-3" and
  category = "required"
}

module Declarations1Package {
  Query declarationsOfAFunctionSameParameterNameQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `declarationsOfAFunctionSameParameterName` query
      TQueryCPP(TDeclarations1PackageQuery(TDeclarationsOfAFunctionSameParameterNameQuery()))
  }
}
