//** THIS FILE IS AUTOGENERATED, DO NOT MODIFY DIRECTLY.  **/
import cpp
import RuleMetadata
import codingstandards.cpp.exclusions.RuleMetadata

newtype Declarations7Query = TUninitializedVariableQuery()

predicate isDeclarations7QueryMetadata(Query query, string queryId, string ruleId, string category) {
  query =
    // `Query` instance for the `uninitializedVariable` query
    Declarations7Package::uninitializedVariableQuery() and
  queryId =
    // `@id` for the `uninitializedVariable` query
    "cpp/misra/uninitialized-variable" and
  ruleId = "RULE-11-6-1" and
  category = "advisory"
}

module Declarations7Package {
  Query uninitializedVariableQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `uninitializedVariable` query
      TQueryCPP(TDeclarations7PackageQuery(TUninitializedVariableQuery()))
  }
}
