//** THIS FILE IS AUTOGENERATED, DO NOT MODIFY DIRECTLY.  **/
import cpp
import RuleMetadata
import codingstandards.cpp.exclusions.RuleMetadata

newtype Declarations3Query =
  TVariableDeclaredArrayTypeQuery() or
  TBlockScopeFunctionAmbiguousQuery() or
  TBlockScopeObjectAmbiguousQuery()

predicate isDeclarations3QueryMetadata(Query query, string queryId, string ruleId, string category) {
  query =
    // `Query` instance for the `variableDeclaredArrayType` query
    Declarations3Package::variableDeclaredArrayTypeQuery() and
  queryId =
    // `@id` for the `variableDeclaredArrayType` query
    "cpp/misra/variable-declared-array-type" and
  ruleId = "RULE-11-3-1" and
  category = "advisory"
  or
  query =
    // `Query` instance for the `blockScopeFunctionAmbiguous` query
    Declarations3Package::blockScopeFunctionAmbiguousQuery() and
  queryId =
    // `@id` for the `blockScopeFunctionAmbiguous` query
    "cpp/misra/block-scope-function-ambiguous" and
  ruleId = "RULE-6-0-1" and
  category = "required"
  or
  query =
    // `Query` instance for the `blockScopeObjectAmbiguous` query
    Declarations3Package::blockScopeObjectAmbiguousQuery() and
  queryId =
    // `@id` for the `blockScopeObjectAmbiguous` query
    "cpp/misra/block-scope-object-ambiguous" and
  ruleId = "RULE-6-0-1" and
  category = "required"
}

module Declarations3Package {
  Query variableDeclaredArrayTypeQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `variableDeclaredArrayType` query
      TQueryCPP(TDeclarations3PackageQuery(TVariableDeclaredArrayTypeQuery()))
  }

  Query blockScopeFunctionAmbiguousQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `blockScopeFunctionAmbiguous` query
      TQueryCPP(TDeclarations3PackageQuery(TBlockScopeFunctionAmbiguousQuery()))
  }

  Query blockScopeObjectAmbiguousQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `blockScopeObjectAmbiguous` query
      TQueryCPP(TDeclarations3PackageQuery(TBlockScopeObjectAmbiguousQuery()))
  }
}
