//** THIS FILE IS AUTOGENERATED, DO NOT MODIFY DIRECTLY.  **/
import cpp
import RuleMetadata
import codingstandards.cpp.exclusions.RuleMetadata

newtype Declarations8Query =
  TSourceCodeImplementedOnlyOnceQuery() or
  TTemplateSpecializationWrongLocationQuery() or
  TDuplicateTypeDefinitionsQuery()

predicate isDeclarations8QueryMetadata(Query query, string queryId, string ruleId, string category) {
  query =
    // `Query` instance for the `sourceCodeImplementedOnlyOnce` query
    Declarations8Package::sourceCodeImplementedOnlyOnceQuery() and
  queryId =
    // `@id` for the `sourceCodeImplementedOnlyOnce` query
    "cpp/misra/source-code-implemented-only-once" and
  ruleId = "RULE-6-2-3" and
  category = "required"
  or
  query =
    // `Query` instance for the `templateSpecializationWrongLocation` query
    Declarations8Package::templateSpecializationWrongLocationQuery() and
  queryId =
    // `@id` for the `templateSpecializationWrongLocation` query
    "cpp/misra/template-specialization-wrong-location" and
  ruleId = "RULE-6-2-3" and
  category = "required"
  or
  query =
    // `Query` instance for the `duplicateTypeDefinitions` query
    Declarations8Package::duplicateTypeDefinitionsQuery() and
  queryId =
    // `@id` for the `duplicateTypeDefinitions` query
    "cpp/misra/duplicate-type-definitions" and
  ruleId = "RULE-6-2-3" and
  category = "required"
}

module Declarations8Package {
  Query sourceCodeImplementedOnlyOnceQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `sourceCodeImplementedOnlyOnce` query
      TQueryCPP(TDeclarations8PackageQuery(TSourceCodeImplementedOnlyOnceQuery()))
  }

  Query templateSpecializationWrongLocationQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `templateSpecializationWrongLocation` query
      TQueryCPP(TDeclarations8PackageQuery(TTemplateSpecializationWrongLocationQuery()))
  }

  Query duplicateTypeDefinitionsQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `duplicateTypeDefinitions` query
      TQueryCPP(TDeclarations8PackageQuery(TDuplicateTypeDefinitionsQuery()))
  }
}
