//** THIS FILE IS AUTOGENERATED, DO NOT MODIFY DIRECTLY.  **/
import cpp
import RuleMetadata
import codingstandards.cpp.exclusions.RuleMetadata

newtype Declarations5Query =
  TMemberFunctionsRefqualifiedQuery() or
  TTypeAliasesDeclarationQuery()

predicate isDeclarations5QueryMetadata(Query query, string queryId, string ruleId, string category) {
  query =
    // `Query` instance for the `memberFunctionsRefqualified` query
    Declarations5Package::memberFunctionsRefqualifiedQuery() and
  queryId =
    // `@id` for the `memberFunctionsRefqualified` query
    "cpp/misra/member-functions-refqualified" and
  ruleId = "RULE-6-8-4" and
  category = "advisory"
  or
  query =
    // `Query` instance for the `typeAliasesDeclaration` query
    Declarations5Package::typeAliasesDeclarationQuery() and
  queryId =
    // `@id` for the `typeAliasesDeclaration` query
    "cpp/misra/type-aliases-declaration" and
  ruleId = "RULE-6-9-1" and
  category = "required"
}

module Declarations5Package {
  Query memberFunctionsRefqualifiedQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `memberFunctionsRefqualified` query
      TQueryCPP(TDeclarations5PackageQuery(TMemberFunctionsRefqualifiedQuery()))
  }

  Query typeAliasesDeclarationQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `typeAliasesDeclaration` query
      TQueryCPP(TDeclarations5PackageQuery(TTypeAliasesDeclarationQuery()))
  }
}
