//** THIS FILE IS AUTOGENERATED, DO NOT MODIFY DIRECTLY.  **/
import cpp
import RuleMetadata
import codingstandards.cpp.exclusions.RuleMetadata

newtype IOQuery =
  TInterleavedInputOutputWithoutFlushQuery() or
  TInterleavedInputOutputWithoutPositionQuery() or
  TCloseFilesWhenTheyAreNoLongerNeededQuery()

predicate isIOQueryMetadata(Query query, string queryId, string ruleId, string category) {
  query =
    // `Query` instance for the `interleavedInputOutputWithoutFlush` query
    IOPackage::interleavedInputOutputWithoutFlushQuery() and
  queryId =
    // `@id` for the `interleavedInputOutputWithoutFlush` query
    "cpp/autosar/interleaved-input-output-without-flush" and
  ruleId = "A27-0-3" and
  category = "required"
  or
  query =
    // `Query` instance for the `interleavedInputOutputWithoutPosition` query
    IOPackage::interleavedInputOutputWithoutPositionQuery() and
  queryId =
    // `@id` for the `interleavedInputOutputWithoutPosition` query
    "cpp/cert/interleaved-input-output-without-position" and
  ruleId = "FIO50-CPP" and
  category = "rule"
  or
  query =
    // `Query` instance for the `closeFilesWhenTheyAreNoLongerNeeded` query
    IOPackage::closeFilesWhenTheyAreNoLongerNeededQuery() and
  queryId =
    // `@id` for the `closeFilesWhenTheyAreNoLongerNeeded` query
    "cpp/cert/close-files-when-they-are-no-longer-needed" and
  ruleId = "FIO51-CPP" and
  category = "rule"
}

module IOPackage {
  Query interleavedInputOutputWithoutFlushQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `interleavedInputOutputWithoutFlush` query
      TQueryCPP(TIOPackageQuery(TInterleavedInputOutputWithoutFlushQuery()))
  }

  Query interleavedInputOutputWithoutPositionQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `interleavedInputOutputWithoutPosition` query
      TQueryCPP(TIOPackageQuery(TInterleavedInputOutputWithoutPositionQuery()))
  }

  Query closeFilesWhenTheyAreNoLongerNeededQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `closeFilesWhenTheyAreNoLongerNeeded` query
      TQueryCPP(TIOPackageQuery(TCloseFilesWhenTheyAreNoLongerNeededQuery()))
  }
}
