//** THIS FILE IS AUTOGENERATED, DO NOT MODIFY DIRECTLY.  **/
import cpp
import RuleMetadata
import codingstandards.cpp.exclusions.RuleMetadata

newtype LifetimeQuery =
  TValueOfAnObjectMustNotBeReadBeforeItHasBeenSetQuery() or
  TAutomaticStorageAssignedToObjectGreaterLifetimeQuery()

predicate isLifetimeQueryMetadata(Query query, string queryId, string ruleId, string category) {
  query =
    // `Query` instance for the `valueOfAnObjectMustNotBeReadBeforeItHasBeenSet` query
    LifetimePackage::valueOfAnObjectMustNotBeReadBeforeItHasBeenSetQuery() and
  queryId =
    // `@id` for the `valueOfAnObjectMustNotBeReadBeforeItHasBeenSet` query
    "cpp/misra/value-of-an-object-must-not-be-read-before-it-has-been-set" and
  ruleId = "RULE-11-6-2" and
  category = "mandatory"
  or
  query =
    // `Query` instance for the `automaticStorageAssignedToObjectGreaterLifetime` query
    LifetimePackage::automaticStorageAssignedToObjectGreaterLifetimeQuery() and
  queryId =
    // `@id` for the `automaticStorageAssignedToObjectGreaterLifetime` query
    "cpp/misra/automatic-storage-assigned-to-object-greater-lifetime" and
  ruleId = "RULE-6-8-3" and
  category = "required"
}

module LifetimePackage {
  Query valueOfAnObjectMustNotBeReadBeforeItHasBeenSetQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `valueOfAnObjectMustNotBeReadBeforeItHasBeenSet` query
      TQueryCPP(TLifetimePackageQuery(TValueOfAnObjectMustNotBeReadBeforeItHasBeenSetQuery()))
  }

  Query automaticStorageAssignedToObjectGreaterLifetimeQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `automaticStorageAssignedToObjectGreaterLifetime` query
      TQueryCPP(TLifetimePackageQuery(TAutomaticStorageAssignedToObjectGreaterLifetimeQuery()))
  }
}
