//** THIS FILE IS AUTOGENERATED, DO NOT MODIFY DIRECTLY.  **/
import cpp
import RuleMetadata
import codingstandards.cpp.exclusions.RuleMetadata

newtype Memory3Query = TPointerComparedBetweenDifferentArraysQuery()

predicate isMemory3QueryMetadata(Query query, string queryId, string ruleId, string category) {
  query =
    // `Query` instance for the `pointerComparedBetweenDifferentArrays` query
    Memory3Package::pointerComparedBetweenDifferentArraysQuery() and
  queryId =
    // `@id` for the `pointerComparedBetweenDifferentArrays` query
    "cpp/misra/pointer-compared-between-different-arrays" and
  ruleId = "RULE-8-9-1" and
  category = "required"
}

module Memory3Package {
  Query pointerComparedBetweenDifferentArraysQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `pointerComparedBetweenDifferentArrays` query
      TQueryCPP(TMemory3PackageQuery(TPointerComparedBetweenDifferentArraysQuery()))
  }
}
