//** THIS FILE IS AUTOGENERATED, DO NOT MODIFY DIRECTLY.  **/
import cpp
import RuleMetadata
import codingstandards.cpp.exclusions.RuleMetadata

newtype Memory2Query = TPointerDifferenceTakenBetweenDifferentArraysQuery()

predicate isMemory2QueryMetadata(Query query, string queryId, string ruleId, string category) {
  query =
    // `Query` instance for the `pointerDifferenceTakenBetweenDifferentArrays` query
    Memory2Package::pointerDifferenceTakenBetweenDifferentArraysQuery() and
  queryId =
    // `@id` for the `pointerDifferenceTakenBetweenDifferentArrays` query
    "cpp/misra/pointer-difference-taken-between-different-arrays" and
  ruleId = "RULE-8-7-2" and
  category = "required"
}

module Memory2Package {
  Query pointerDifferenceTakenBetweenDifferentArraysQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `pointerDifferenceTakenBetweenDifferentArrays` query
      TQueryCPP(TMemory2PackageQuery(TPointerDifferenceTakenBetweenDifferentArraysQuery()))
  }
}
