//** THIS FILE IS AUTOGENERATED, DO NOT MODIFY DIRECTLY.  **/
import cpp
import RuleMetadata
import codingstandards.cpp.exclusions.RuleMetadata

newtype Memory4Query =
  TObjectAssignedToAnOverlappingObjectMisraCppQuery() or
  TObjectCopiedToAnOverlappingObjectMisraCppQuery()

predicate isMemory4QueryMetadata(Query query, string queryId, string ruleId, string category) {
  query =
    // `Query` instance for the `objectAssignedToAnOverlappingObjectMisraCpp` query
    Memory4Package::objectAssignedToAnOverlappingObjectMisraCppQuery() and
  queryId =
    // `@id` for the `objectAssignedToAnOverlappingObjectMisraCpp` query
    "cpp/misra/object-assigned-to-an-overlapping-object-misra-cpp" and
  ruleId = "RULE-8-18-1" and
  category = "mandatory"
  or
  query =
    // `Query` instance for the `objectCopiedToAnOverlappingObjectMisraCpp` query
    Memory4Package::objectCopiedToAnOverlappingObjectMisraCppQuery() and
  queryId =
    // `@id` for the `objectCopiedToAnOverlappingObjectMisraCpp` query
    "cpp/misra/object-copied-to-an-overlapping-object-misra-cpp" and
  ruleId = "RULE-8-18-1" and
  category = "mandatory"
}

module Memory4Package {
  Query objectAssignedToAnOverlappingObjectMisraCppQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `objectAssignedToAnOverlappingObjectMisraCpp` query
      TQueryCPP(TMemory4PackageQuery(TObjectAssignedToAnOverlappingObjectMisraCppQuery()))
  }

  Query objectCopiedToAnOverlappingObjectMisraCppQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `objectCopiedToAnOverlappingObjectMisraCpp` query
      TQueryCPP(TMemory4PackageQuery(TObjectCopiedToAnOverlappingObjectMisraCppQuery()))
  }
}
