//** THIS FILE IS AUTOGENERATED, DO NOT MODIFY DIRECTLY.  **/
import cpp
import RuleMetadata
import codingstandards.cpp.exclusions.RuleMetadata

newtype Memory6Query = TAdvancedMemoryManagementUsedQuery()

predicate isMemory6QueryMetadata(Query query, string queryId, string ruleId, string category) {
  query =
    // `Query` instance for the `advancedMemoryManagementUsed` query
    Memory6Package::advancedMemoryManagementUsedQuery() and
  queryId =
    // `@id` for the `advancedMemoryManagementUsed` query
    "cpp/misra/advanced-memory-management-used" and
  ruleId = "RULE-21-6-3" and
  category = "required"
}

module Memory6Package {
  Query advancedMemoryManagementUsedQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `advancedMemoryManagementUsed` query
      TQueryCPP(TMemory6PackageQuery(TAdvancedMemoryManagementUsedQuery()))
  }
}
