//** THIS FILE IS AUTOGENERATED, DO NOT MODIFY DIRECTLY.  **/
import cpp
import RuleMetadata
import codingstandards.cpp.exclusions.RuleMetadata

newtype OutOfBoundsQuery =
  TContainerAccessWithoutRangeCheckAutosarQuery() or
  TContainerAccessWithoutRangeCheckCertQuery() or
  TGuaranteeGenericCppLibraryFunctionsDoNotOverflowQuery() or
  TRangeCheckStringElementAccessQuery()

predicate isOutOfBoundsQueryMetadata(Query query, string queryId, string ruleId, string category) {
  query =
    // `Query` instance for the `containerAccessWithoutRangeCheckAutosar` query
    OutOfBoundsPackage::containerAccessWithoutRangeCheckAutosarQuery() and
  queryId =
    // `@id` for the `containerAccessWithoutRangeCheckAutosar` query
    "cpp/autosar/container-access-without-range-check-autosar" and
  ruleId = "A5-2-5" and
  category = "required"
  or
  query =
    // `Query` instance for the `containerAccessWithoutRangeCheckCert` query
    OutOfBoundsPackage::containerAccessWithoutRangeCheckCertQuery() and
  queryId =
    // `@id` for the `containerAccessWithoutRangeCheckCert` query
    "cpp/cert/container-access-without-range-check-cert" and
  ruleId = "CTR50-CPP" and
  category = "rule"
  or
  query =
    // `Query` instance for the `guaranteeGenericCppLibraryFunctionsDoNotOverflow` query
    OutOfBoundsPackage::guaranteeGenericCppLibraryFunctionsDoNotOverflowQuery() and
  queryId =
    // `@id` for the `guaranteeGenericCppLibraryFunctionsDoNotOverflow` query
    "cpp/cert/guarantee-generic-cpp-library-functions-do-not-overflow" and
  ruleId = "CTR52-CPP" and
  category = "rule"
  or
  query =
    // `Query` instance for the `rangeCheckStringElementAccess` query
    OutOfBoundsPackage::rangeCheckStringElementAccessQuery() and
  queryId =
    // `@id` for the `rangeCheckStringElementAccess` query
    "cpp/cert/range-check-string-element-access" and
  ruleId = "STR53-CPP" and
  category = "rule"
}

module OutOfBoundsPackage {
  Query containerAccessWithoutRangeCheckAutosarQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `containerAccessWithoutRangeCheckAutosar` query
      TQueryCPP(TOutOfBoundsPackageQuery(TContainerAccessWithoutRangeCheckAutosarQuery()))
  }

  Query containerAccessWithoutRangeCheckCertQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `containerAccessWithoutRangeCheckCert` query
      TQueryCPP(TOutOfBoundsPackageQuery(TContainerAccessWithoutRangeCheckCertQuery()))
  }

  Query guaranteeGenericCppLibraryFunctionsDoNotOverflowQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `guaranteeGenericCppLibraryFunctionsDoNotOverflow` query
      TQueryCPP(TOutOfBoundsPackageQuery(TGuaranteeGenericCppLibraryFunctionsDoNotOverflowQuery()))
  }

  Query rangeCheckStringElementAccessQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `rangeCheckStringElementAccess` query
      TQueryCPP(TOutOfBoundsPackageQuery(TRangeCheckStringElementAccessQuery()))
  }
}
