//** THIS FILE IS AUTOGENERATED, DO NOT MODIFY DIRECTLY.  **/
import cpp
import RuleMetadata
import codingstandards.cpp.exclusions.RuleMetadata

newtype Preconditions5Query = TStdMoveWithNonConstLvalueQuery()

predicate isPreconditions5QueryMetadata(Query query, string queryId, string ruleId, string category) {
  query =
    // `Query` instance for the `stdMoveWithNonConstLvalue` query
    Preconditions5Package::stdMoveWithNonConstLvalueQuery() and
  queryId =
    // `@id` for the `stdMoveWithNonConstLvalue` query
    "cpp/misra/std-move-with-non-const-lvalue" and
  ruleId = "RULE-28-6-1" and
  category = "required"
}

module Preconditions5Package {
  Query stdMoveWithNonConstLvalueQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `stdMoveWithNonConstLvalue` query
      TQueryCPP(TPreconditions5PackageQuery(TStdMoveWithNonConstLvalueQuery()))
  }
}
