//** THIS FILE IS AUTOGENERATED, DO NOT MODIFY DIRECTLY.  **/
import cpp
import RuleMetadata
import codingstandards.cpp.exclusions.RuleMetadata

newtype Preconditions3Query = TAssertMacroUsedWithAConstantExpressionQuery()

predicate isPreconditions3QueryMetadata(Query query, string queryId, string ruleId, string category) {
  query =
    // `Query` instance for the `assertMacroUsedWithAConstantExpression` query
    Preconditions3Package::assertMacroUsedWithAConstantExpressionQuery() and
  queryId =
    // `@id` for the `assertMacroUsedWithAConstantExpression` query
    "cpp/misra/assert-macro-used-with-a-constant-expression" and
  ruleId = "RULE-22-3-1" and
  category = "required"
}

module Preconditions3Package {
  Query assertMacroUsedWithAConstantExpressionQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `assertMacroUsedWithAConstantExpression` query
      TQueryCPP(TPreconditions3PackageQuery(TAssertMacroUsedWithAConstantExpressionQuery()))
  }
}
