//** THIS FILE IS AUTOGENERATED, DO NOT MODIFY DIRECTLY.  **/
import cpp
import RuleMetadata
import codingstandards.cpp.exclusions.RuleMetadata

newtype Preconditions1Query = TPolymorphicClassTypeExpressionInTypeidQuery()

predicate isPreconditions1QueryMetadata(Query query, string queryId, string ruleId, string category) {
  query =
    // `Query` instance for the `polymorphicClassTypeExpressionInTypeid` query
    Preconditions1Package::polymorphicClassTypeExpressionInTypeidQuery() and
  queryId =
    // `@id` for the `polymorphicClassTypeExpressionInTypeid` query
    "cpp/misra/polymorphic-class-type-expression-in-typeid" and
  ruleId = "RULE-8-2-9" and
  category = "required"
}

module Preconditions1Package {
  Query polymorphicClassTypeExpressionInTypeidQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `polymorphicClassTypeExpressionInTypeid` query
      TQueryCPP(TPreconditions1PackageQuery(TPolymorphicClassTypeExpressionInTypeidQuery()))
  }
}
