//** THIS FILE IS AUTOGENERATED, DO NOT MODIFY DIRECTLY.  **/
import cpp
import RuleMetadata
import codingstandards.cpp.exclusions.RuleMetadata

newtype PreprocessorQuery =
  TUndefOfMacroNotDefinedInFileQuery() or
  TInvalidTokenInDefinedOperatorQuery() or
  TDefinedOperatorExpandedInIfDirectiveQuery() or
  TNoValidIfdefGuardInHeaderQuery() or
  TIncludeOutsideGuardQuery()

predicate isPreprocessorQueryMetadata(Query query, string queryId, string ruleId, string category) {
  query =
    // `Query` instance for the `undefOfMacroNotDefinedInFile` query
    PreprocessorPackage::undefOfMacroNotDefinedInFileQuery() and
  queryId =
    // `@id` for the `undefOfMacroNotDefinedInFile` query
    "cpp/misra/undef-of-macro-not-defined-in-file" and
  ruleId = "RULE-19-0-4" and
  category = "advisory"
  or
  query =
    // `Query` instance for the `invalidTokenInDefinedOperator` query
    PreprocessorPackage::invalidTokenInDefinedOperatorQuery() and
  queryId =
    // `@id` for the `invalidTokenInDefinedOperator` query
    "cpp/misra/invalid-token-in-defined-operator" and
  ruleId = "RULE-19-1-1" and
  category = "required"
  or
  query =
    // `Query` instance for the `definedOperatorExpandedInIfDirective` query
    PreprocessorPackage::definedOperatorExpandedInIfDirectiveQuery() and
  queryId =
    // `@id` for the `definedOperatorExpandedInIfDirective` query
    "cpp/misra/defined-operator-expanded-in-if-directive" and
  ruleId = "RULE-19-1-1" and
  category = "required"
  or
  query =
    // `Query` instance for the `noValidIfdefGuardInHeader` query
    PreprocessorPackage::noValidIfdefGuardInHeaderQuery() and
  queryId =
    // `@id` for the `noValidIfdefGuardInHeader` query
    "cpp/misra/no-valid-ifdef-guard-in-header" and
  ruleId = "RULE-19-2-1" and
  category = "required"
  or
  query =
    // `Query` instance for the `includeOutsideGuard` query
    PreprocessorPackage::includeOutsideGuardQuery() and
  queryId =
    // `@id` for the `includeOutsideGuard` query
    "cpp/misra/include-outside-guard" and
  ruleId = "RULE-19-2-1" and
  category = "required"
}

module PreprocessorPackage {
  Query undefOfMacroNotDefinedInFileQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `undefOfMacroNotDefinedInFile` query
      TQueryCPP(TPreprocessorPackageQuery(TUndefOfMacroNotDefinedInFileQuery()))
  }

  Query invalidTokenInDefinedOperatorQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `invalidTokenInDefinedOperator` query
      TQueryCPP(TPreprocessorPackageQuery(TInvalidTokenInDefinedOperatorQuery()))
  }

  Query definedOperatorExpandedInIfDirectiveQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `definedOperatorExpandedInIfDirective` query
      TQueryCPP(TPreprocessorPackageQuery(TDefinedOperatorExpandedInIfDirectiveQuery()))
  }

  Query noValidIfdefGuardInHeaderQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `noValidIfdefGuardInHeader` query
      TQueryCPP(TPreprocessorPackageQuery(TNoValidIfdefGuardInHeaderQuery()))
  }

  Query includeOutsideGuardQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `includeOutsideGuard` query
      TQueryCPP(TPreprocessorPackageQuery(TIncludeOutsideGuardQuery()))
  }
}
