//** THIS FILE IS AUTOGENERATED, DO NOT MODIFY DIRECTLY.  **/
import cpp
import codingstandards.cpp.exclusions.RuleMetadata
//** Import packages for this language **/
import Allocations
import BannedFunctions
import BannedLibraries
import BannedSyntax
import BannedTypes
import Classes
import Comments
import Concurrency
import Conditionals
import Const
import DeadCode
import Declarations
import ExceptionSafety
import Exceptions1
import Exceptions2
import Expressions
import Freed
import Functions
import IO
import Includes
import Inheritance
import Initialization
import IntegerConversion
import Invariants
import Iterators
import Lambdas
import Literals
import Loops
import Macros
import MoveForward
import Naming
import Null
import OperatorInvariants
import Operators
import OrderOfEvaluation
import OutOfBounds
import Pointers
import Representation
import Scope
import SideEffects1
import SideEffects2
import SmartPointers1
import SmartPointers2
import Strings
import Templates
import Toolchain
import TrustBoundaries
import TypeRanges
import Uninitialized
import VirtualFunctions

/** The TQuery type representing this language * */
newtype TCPPQuery =
  TAllocationsPackageQuery(AllocationsQuery q) or
  TBannedFunctionsPackageQuery(BannedFunctionsQuery q) or
  TBannedLibrariesPackageQuery(BannedLibrariesQuery q) or
  TBannedSyntaxPackageQuery(BannedSyntaxQuery q) or
  TBannedTypesPackageQuery(BannedTypesQuery q) or
  TClassesPackageQuery(ClassesQuery q) or
  TCommentsPackageQuery(CommentsQuery q) or
  TConcurrencyPackageQuery(ConcurrencyQuery q) or
  TConditionalsPackageQuery(ConditionalsQuery q) or
  TConstPackageQuery(ConstQuery q) or
  TDeadCodePackageQuery(DeadCodeQuery q) or
  TDeclarationsPackageQuery(DeclarationsQuery q) or
  TExceptionSafetyPackageQuery(ExceptionSafetyQuery q) or
  TExceptions1PackageQuery(Exceptions1Query q) or
  TExceptions2PackageQuery(Exceptions2Query q) or
  TExpressionsPackageQuery(ExpressionsQuery q) or
  TFreedPackageQuery(FreedQuery q) or
  TFunctionsPackageQuery(FunctionsQuery q) or
  TIOPackageQuery(IOQuery q) or
  TIncludesPackageQuery(IncludesQuery q) or
  TInheritancePackageQuery(InheritanceQuery q) or
  TInitializationPackageQuery(InitializationQuery q) or
  TIntegerConversionPackageQuery(IntegerConversionQuery q) or
  TInvariantsPackageQuery(InvariantsQuery q) or
  TIteratorsPackageQuery(IteratorsQuery q) or
  TLambdasPackageQuery(LambdasQuery q) or
  TLiteralsPackageQuery(LiteralsQuery q) or
  TLoopsPackageQuery(LoopsQuery q) or
  TMacrosPackageQuery(MacrosQuery q) or
  TMoveForwardPackageQuery(MoveForwardQuery q) or
  TNamingPackageQuery(NamingQuery q) or
  TNullPackageQuery(NullQuery q) or
  TOperatorInvariantsPackageQuery(OperatorInvariantsQuery q) or
  TOperatorsPackageQuery(OperatorsQuery q) or
  TOrderOfEvaluationPackageQuery(OrderOfEvaluationQuery q) or
  TOutOfBoundsPackageQuery(OutOfBoundsQuery q) or
  TPointersPackageQuery(PointersQuery q) or
  TRepresentationPackageQuery(RepresentationQuery q) or
  TScopePackageQuery(ScopeQuery q) or
  TSideEffects1PackageQuery(SideEffects1Query q) or
  TSideEffects2PackageQuery(SideEffects2Query q) or
  TSmartPointers1PackageQuery(SmartPointers1Query q) or
  TSmartPointers2PackageQuery(SmartPointers2Query q) or
  TStringsPackageQuery(StringsQuery q) or
  TTemplatesPackageQuery(TemplatesQuery q) or
  TToolchainPackageQuery(ToolchainQuery q) or
  TTrustBoundariesPackageQuery(TrustBoundariesQuery q) or
  TTypeRangesPackageQuery(TypeRangesQuery q) or
  TUninitializedPackageQuery(UninitializedQuery q) or
  TVirtualFunctionsPackageQuery(VirtualFunctionsQuery q)

/** The metadata predicate * */
predicate isQueryMetadata(Query query, string queryId, string ruleId) {
  isAllocationsQueryMetadata(query, queryId, ruleId) or
  isBannedFunctionsQueryMetadata(query, queryId, ruleId) or
  isBannedLibrariesQueryMetadata(query, queryId, ruleId) or
  isBannedSyntaxQueryMetadata(query, queryId, ruleId) or
  isBannedTypesQueryMetadata(query, queryId, ruleId) or
  isClassesQueryMetadata(query, queryId, ruleId) or
  isCommentsQueryMetadata(query, queryId, ruleId) or
  isConcurrencyQueryMetadata(query, queryId, ruleId) or
  isConditionalsQueryMetadata(query, queryId, ruleId) or
  isConstQueryMetadata(query, queryId, ruleId) or
  isDeadCodeQueryMetadata(query, queryId, ruleId) or
  isDeclarationsQueryMetadata(query, queryId, ruleId) or
  isExceptionSafetyQueryMetadata(query, queryId, ruleId) or
  isExceptions1QueryMetadata(query, queryId, ruleId) or
  isExceptions2QueryMetadata(query, queryId, ruleId) or
  isExpressionsQueryMetadata(query, queryId, ruleId) or
  isFreedQueryMetadata(query, queryId, ruleId) or
  isFunctionsQueryMetadata(query, queryId, ruleId) or
  isIOQueryMetadata(query, queryId, ruleId) or
  isIncludesQueryMetadata(query, queryId, ruleId) or
  isInheritanceQueryMetadata(query, queryId, ruleId) or
  isInitializationQueryMetadata(query, queryId, ruleId) or
  isIntegerConversionQueryMetadata(query, queryId, ruleId) or
  isInvariantsQueryMetadata(query, queryId, ruleId) or
  isIteratorsQueryMetadata(query, queryId, ruleId) or
  isLambdasQueryMetadata(query, queryId, ruleId) or
  isLiteralsQueryMetadata(query, queryId, ruleId) or
  isLoopsQueryMetadata(query, queryId, ruleId) or
  isMacrosQueryMetadata(query, queryId, ruleId) or
  isMoveForwardQueryMetadata(query, queryId, ruleId) or
  isNamingQueryMetadata(query, queryId, ruleId) or
  isNullQueryMetadata(query, queryId, ruleId) or
  isOperatorInvariantsQueryMetadata(query, queryId, ruleId) or
  isOperatorsQueryMetadata(query, queryId, ruleId) or
  isOrderOfEvaluationQueryMetadata(query, queryId, ruleId) or
  isOutOfBoundsQueryMetadata(query, queryId, ruleId) or
  isPointersQueryMetadata(query, queryId, ruleId) or
  isRepresentationQueryMetadata(query, queryId, ruleId) or
  isScopeQueryMetadata(query, queryId, ruleId) or
  isSideEffects1QueryMetadata(query, queryId, ruleId) or
  isSideEffects2QueryMetadata(query, queryId, ruleId) or
  isSmartPointers1QueryMetadata(query, queryId, ruleId) or
  isSmartPointers2QueryMetadata(query, queryId, ruleId) or
  isStringsQueryMetadata(query, queryId, ruleId) or
  isTemplatesQueryMetadata(query, queryId, ruleId) or
  isToolchainQueryMetadata(query, queryId, ruleId) or
  isTrustBoundariesQueryMetadata(query, queryId, ruleId) or
  isTypeRangesQueryMetadata(query, queryId, ruleId) or
  isUninitializedQueryMetadata(query, queryId, ruleId) or
  isVirtualFunctionsQueryMetadata(query, queryId, ruleId)
}
