//** THIS FILE IS AUTOGENERATED, DO NOT MODIFY DIRECTLY.  **/
import cpp
import codingstandards.cpp.exclusions.RuleMetadata
//** Import packages for this language **/
import Allocations
import BannedAPIs
import BannedFunctions
import BannedLibraries
import BannedSyntax
import BannedTypes
import Classes
import Classes2
import Comments
import Concurrency
import Conditionals
import Const
import Conversions
import Conversions2
import DeadCode
import DeadCode3
import DeadCode4
import DeadCode7
import Declarations
import ExceptionSafety
import Exceptions1
import Exceptions2
import Exceptions3
import Expressions
import FloatingPoint
import Freed
import Functions
import IO
import ImportMisra23
import Includes
import Inheritance
import Initialization
import IntegerConversion
import Invariants
import Iterators
import Lambdas
import Linkage1
import Linkage2
import Literals
import Loops
import Macros
import Memory2
import Memory3
import Memory4
import MoveForward
import Naming
import Naming2
import Null
import OperatorInvariants
import Operators
import OrderOfEvaluation
import OutOfBounds
import Pointers
import Preconditions1
import Preconditions4
import Representation
import Scope
import SideEffects1
import SideEffects2
import SmartPointers1
import SmartPointers2
import Statements
import Strings
import Templates
import Toolchain
import Trigraph
import TrustBoundaries
import TypeRanges
import Uninitialized
import VirtualFunctions

/** The TQuery type representing this language * */
newtype TCPPQuery =
  TAllocationsPackageQuery(AllocationsQuery q) or
  TBannedAPIsPackageQuery(BannedAPIsQuery q) or
  TBannedFunctionsPackageQuery(BannedFunctionsQuery q) or
  TBannedLibrariesPackageQuery(BannedLibrariesQuery q) or
  TBannedSyntaxPackageQuery(BannedSyntaxQuery q) or
  TBannedTypesPackageQuery(BannedTypesQuery q) or
  TClassesPackageQuery(ClassesQuery q) or
  TClasses2PackageQuery(Classes2Query q) or
  TCommentsPackageQuery(CommentsQuery q) or
  TConcurrencyPackageQuery(ConcurrencyQuery q) or
  TConditionalsPackageQuery(ConditionalsQuery q) or
  TConstPackageQuery(ConstQuery q) or
  TConversionsPackageQuery(ConversionsQuery q) or
  TConversions2PackageQuery(Conversions2Query q) or
  TDeadCodePackageQuery(DeadCodeQuery q) or
  TDeadCode3PackageQuery(DeadCode3Query q) or
  TDeadCode4PackageQuery(DeadCode4Query q) or
  TDeadCode7PackageQuery(DeadCode7Query q) or
  TDeclarationsPackageQuery(DeclarationsQuery q) or
  TExceptionSafetyPackageQuery(ExceptionSafetyQuery q) or
  TExceptions1PackageQuery(Exceptions1Query q) or
  TExceptions2PackageQuery(Exceptions2Query q) or
  TExceptions3PackageQuery(Exceptions3Query q) or
  TExpressionsPackageQuery(ExpressionsQuery q) or
  TFloatingPointPackageQuery(FloatingPointQuery q) or
  TFreedPackageQuery(FreedQuery q) or
  TFunctionsPackageQuery(FunctionsQuery q) or
  TIOPackageQuery(IOQuery q) or
  TImportMisra23PackageQuery(ImportMisra23Query q) or
  TIncludesPackageQuery(IncludesQuery q) or
  TInheritancePackageQuery(InheritanceQuery q) or
  TInitializationPackageQuery(InitializationQuery q) or
  TIntegerConversionPackageQuery(IntegerConversionQuery q) or
  TInvariantsPackageQuery(InvariantsQuery q) or
  TIteratorsPackageQuery(IteratorsQuery q) or
  TLambdasPackageQuery(LambdasQuery q) or
  TLinkage1PackageQuery(Linkage1Query q) or
  TLinkage2PackageQuery(Linkage2Query q) or
  TLiteralsPackageQuery(LiteralsQuery q) or
  TLoopsPackageQuery(LoopsQuery q) or
  TMacrosPackageQuery(MacrosQuery q) or
  TMemory2PackageQuery(Memory2Query q) or
  TMemory3PackageQuery(Memory3Query q) or
  TMemory4PackageQuery(Memory4Query q) or
  TMoveForwardPackageQuery(MoveForwardQuery q) or
  TNamingPackageQuery(NamingQuery q) or
  TNaming2PackageQuery(Naming2Query q) or
  TNullPackageQuery(NullQuery q) or
  TOperatorInvariantsPackageQuery(OperatorInvariantsQuery q) or
  TOperatorsPackageQuery(OperatorsQuery q) or
  TOrderOfEvaluationPackageQuery(OrderOfEvaluationQuery q) or
  TOutOfBoundsPackageQuery(OutOfBoundsQuery q) or
  TPointersPackageQuery(PointersQuery q) or
  TPreconditions1PackageQuery(Preconditions1Query q) or
  TPreconditions4PackageQuery(Preconditions4Query q) or
  TRepresentationPackageQuery(RepresentationQuery q) or
  TScopePackageQuery(ScopeQuery q) or
  TSideEffects1PackageQuery(SideEffects1Query q) or
  TSideEffects2PackageQuery(SideEffects2Query q) or
  TSmartPointers1PackageQuery(SmartPointers1Query q) or
  TSmartPointers2PackageQuery(SmartPointers2Query q) or
  TStatementsPackageQuery(StatementsQuery q) or
  TStringsPackageQuery(StringsQuery q) or
  TTemplatesPackageQuery(TemplatesQuery q) or
  TToolchainPackageQuery(ToolchainQuery q) or
  TTrigraphPackageQuery(TrigraphQuery q) or
  TTrustBoundariesPackageQuery(TrustBoundariesQuery q) or
  TTypeRangesPackageQuery(TypeRangesQuery q) or
  TUninitializedPackageQuery(UninitializedQuery q) or
  TVirtualFunctionsPackageQuery(VirtualFunctionsQuery q)

/** The metadata predicate * */
predicate isQueryMetadata(Query query, string queryId, string ruleId, string category) {
  isAllocationsQueryMetadata(query, queryId, ruleId, category) or
  isBannedAPIsQueryMetadata(query, queryId, ruleId, category) or
  isBannedFunctionsQueryMetadata(query, queryId, ruleId, category) or
  isBannedLibrariesQueryMetadata(query, queryId, ruleId, category) or
  isBannedSyntaxQueryMetadata(query, queryId, ruleId, category) or
  isBannedTypesQueryMetadata(query, queryId, ruleId, category) or
  isClassesQueryMetadata(query, queryId, ruleId, category) or
  isClasses2QueryMetadata(query, queryId, ruleId, category) or
  isCommentsQueryMetadata(query, queryId, ruleId, category) or
  isConcurrencyQueryMetadata(query, queryId, ruleId, category) or
  isConditionalsQueryMetadata(query, queryId, ruleId, category) or
  isConstQueryMetadata(query, queryId, ruleId, category) or
  isConversionsQueryMetadata(query, queryId, ruleId, category) or
  isConversions2QueryMetadata(query, queryId, ruleId, category) or
  isDeadCodeQueryMetadata(query, queryId, ruleId, category) or
  isDeadCode3QueryMetadata(query, queryId, ruleId, category) or
  isDeadCode4QueryMetadata(query, queryId, ruleId, category) or
  isDeadCode7QueryMetadata(query, queryId, ruleId, category) or
  isDeclarationsQueryMetadata(query, queryId, ruleId, category) or
  isExceptionSafetyQueryMetadata(query, queryId, ruleId, category) or
  isExceptions1QueryMetadata(query, queryId, ruleId, category) or
  isExceptions2QueryMetadata(query, queryId, ruleId, category) or
  isExceptions3QueryMetadata(query, queryId, ruleId, category) or
  isExpressionsQueryMetadata(query, queryId, ruleId, category) or
  isFloatingPointQueryMetadata(query, queryId, ruleId, category) or
  isFreedQueryMetadata(query, queryId, ruleId, category) or
  isFunctionsQueryMetadata(query, queryId, ruleId, category) or
  isIOQueryMetadata(query, queryId, ruleId, category) or
  isImportMisra23QueryMetadata(query, queryId, ruleId, category) or
  isIncludesQueryMetadata(query, queryId, ruleId, category) or
  isInheritanceQueryMetadata(query, queryId, ruleId, category) or
  isInitializationQueryMetadata(query, queryId, ruleId, category) or
  isIntegerConversionQueryMetadata(query, queryId, ruleId, category) or
  isInvariantsQueryMetadata(query, queryId, ruleId, category) or
  isIteratorsQueryMetadata(query, queryId, ruleId, category) or
  isLambdasQueryMetadata(query, queryId, ruleId, category) or
  isLinkage1QueryMetadata(query, queryId, ruleId, category) or
  isLinkage2QueryMetadata(query, queryId, ruleId, category) or
  isLiteralsQueryMetadata(query, queryId, ruleId, category) or
  isLoopsQueryMetadata(query, queryId, ruleId, category) or
  isMacrosQueryMetadata(query, queryId, ruleId, category) or
  isMemory2QueryMetadata(query, queryId, ruleId, category) or
  isMemory3QueryMetadata(query, queryId, ruleId, category) or
  isMemory4QueryMetadata(query, queryId, ruleId, category) or
  isMoveForwardQueryMetadata(query, queryId, ruleId, category) or
  isNamingQueryMetadata(query, queryId, ruleId, category) or
  isNaming2QueryMetadata(query, queryId, ruleId, category) or
  isNullQueryMetadata(query, queryId, ruleId, category) or
  isOperatorInvariantsQueryMetadata(query, queryId, ruleId, category) or
  isOperatorsQueryMetadata(query, queryId, ruleId, category) or
  isOrderOfEvaluationQueryMetadata(query, queryId, ruleId, category) or
  isOutOfBoundsQueryMetadata(query, queryId, ruleId, category) or
  isPointersQueryMetadata(query, queryId, ruleId, category) or
  isPreconditions1QueryMetadata(query, queryId, ruleId, category) or
  isPreconditions4QueryMetadata(query, queryId, ruleId, category) or
  isRepresentationQueryMetadata(query, queryId, ruleId, category) or
  isScopeQueryMetadata(query, queryId, ruleId, category) or
  isSideEffects1QueryMetadata(query, queryId, ruleId, category) or
  isSideEffects2QueryMetadata(query, queryId, ruleId, category) or
  isSmartPointers1QueryMetadata(query, queryId, ruleId, category) or
  isSmartPointers2QueryMetadata(query, queryId, ruleId, category) or
  isStatementsQueryMetadata(query, queryId, ruleId, category) or
  isStringsQueryMetadata(query, queryId, ruleId, category) or
  isTemplatesQueryMetadata(query, queryId, ruleId, category) or
  isToolchainQueryMetadata(query, queryId, ruleId, category) or
  isTrigraphQueryMetadata(query, queryId, ruleId, category) or
  isTrustBoundariesQueryMetadata(query, queryId, ruleId, category) or
  isTypeRangesQueryMetadata(query, queryId, ruleId, category) or
  isUninitializedQueryMetadata(query, queryId, ruleId, category) or
  isVirtualFunctionsQueryMetadata(query, queryId, ruleId, category)
}
