//** THIS FILE IS AUTOGENERATED, DO NOT MODIFY DIRECTLY.  **/
import cpp
import RuleMetadata
import codingstandards.cpp.exclusions.RuleMetadata

newtype SideEffects5Query = TShortCircuitedPersistentSideEffectQuery()

predicate isSideEffects5QueryMetadata(Query query, string queryId, string ruleId, string category) {
  query =
    // `Query` instance for the `shortCircuitedPersistentSideEffect` query
    SideEffects5Package::shortCircuitedPersistentSideEffectQuery() and
  queryId =
    // `@id` for the `shortCircuitedPersistentSideEffect` query
    "cpp/misra/short-circuited-persistent-side-effect" and
  ruleId = "RULE-8-14-1" and
  category = "advisory"
}

module SideEffects5Package {
  Query shortCircuitedPersistentSideEffectQuery() {
    //autogenerate `Query` type
    result =
      // `Query` type for `shortCircuitedPersistentSideEffect` query
      TQueryCPP(TSideEffects5PackageQuery(TShortCircuitedPersistentSideEffectQuery()))
  }
}
