name: Create draft release

on:
  workflow_dispatch:
    inputs:
      release_version_tag:
        description: |
          The tag for the new draft release, e.g. v0.5.1 (exact string, including the v).
        required: true

      previous_release_version_tag:
        description: |
          The tag preceding this release, e.g. v0.5.0 (exact string, including the v).
        required: true

      codeql_analysis_threads:
        description: |
          Number of threads to evaluate queries
        required: true
        default: 6
      aws_ec2_instance_type:
        description: |
          Recommended specs: 8+ vCPU 32+ GB RAM (e.g. t2.2xlarge, r5.2xlarge)
        required: true
        default: r5.2xlarge

jobs:
  create-draft-release:
    name: Create draft release
    runs-on: ubuntu-latest
    env:      
      # AWS CONFIGURATION
      AWS_EC2_INSTANCE_TYPE: ${{ github.event.inputs.aws_ec2_instance_type }}

      # CODEQL CONFIGURATION
      CODEQL_ANALYSIS_THREADS: ${{ github.event.inputs.codeql_analysis_threads }}
      
      # INTEGRATION TESTING CONFIGURATION
      INTEGRATION_TESTING_ACCESS_TOKEN: ${{ secrets.INTEGRATION_TESTING_ACCESS_TOKEN }}
      WORKFLOW_ID: 11846210
      
      # RELEASE VERSION TAG
      RELEASE_VERSION_TAG: ${{ github.event.inputs.release_version_tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install generate_release_notes.py dependencies
        run: pip install -r scripts/requirements.txt

      - name: Create draft release
        run: |
          scripts/release/create_draft_release.sh ${GITHUB_REF#refs/heads/} "$RELEASE_VERSION_TAG" "$PREVIOUS_RELEASE_VERSION_TAG"
        env:
          GITHUB_TOKEN: ${{ github.token }}
