name: Generate HTML documentation
permissions:
  contents: read

on:
  merge_group:
    types: [checks_requested]
  push:
    branches:
      - main
      - 'rc/**'
      - next
  pull_request:
    branches:
      - main
      - 'rc/**'
      - next

jobs:
  generate-html-doc:
    name: Generate HTML documentation
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: Install Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: "3.9"

      - name: Install generate_iso26262_docs.py dependencies
        run: pip install -r scripts/requirements.txt

      - name: Generate documentation
        run: |
          python scripts/documentation/generate_iso26262_docs.py coding-standards-html-docs

      - name: Upload HTML documentation
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: coding-standards-docs-${{ github.sha }}
          path: coding-standards-html-docs/
